daemon:
    name: Astron Cluster

general:
    eventlogger: 127.0.0.1:7197
    dc_files:
        - ../../resources/phase_3/etc/otp.dc
        - ../../resources/phase_3/etc/toon.dc

messagedirector:
    bind: 127.0.0.1:7198
    #threaded: true

uberdogs:
    - class: CentralLogger
      id: 4688
      anonymous: false

    - class: ClientServicesManager
      id: 4665
      anonymous: true
      
    - class: DistributedDeliveryManager
      id: 4683
      anonymous: false
      
    - class: ChatAgent
      id: 4681
      anonymous: false
      
    - class: TTSpeedchatRelay
      id: 4712
      anonymous: false

roles:
    - type: clientagent
      bind: 127.0.0.1:6667
      version: "ttc-alpha-v1.0.0"
      #tls:
      #  certificate: "tls/gameserver.crt"
      #  key_file: "tls/gameserver.key"
      #  chain_file: "tls/gameserver.crt"
      #  tlsv1: false
      #  sslv2: false
      #  sslv3: true
      #  cert_authority: "tls/gameserver.pem"
      #  max_verify_depth: 2
      client:
       relocate: true
       add_interest: enabled
      channels:
        min: 1000000000
        max: 1009999999

    - type: stateserver
      control: 10000

    - type: database
      control: 4003
      generate:
        min: 100000000
        max: 399999999
      backend:
        type: yaml
        foldername: databases/astrondb

    - type: dbss
      database: 4003
      ranges:
        - min: 100000000
          max: 399999999

    - type: eventlogger
      bind: 127.0.0.1:7197
      output: logs/events-%y%m%d_%H%M%S.log
