# Window:
window-title Toontown Classic [BETA 1]
load-display pandadx9

# Models:
model-path resources
model-path resources/phase_3
model-path resources/phase_4
model-path resources/phase_5
model-path resources/phase_6
model-path resources/phase_7
model-path resources/phase_8
model-path resources/phase_9
model-path resources/phase_10
model-path resources/phase_11
model-path resources/phase_12
model-path resources/phase_13

# Audio:
audio-library-name p3fmod_audio

# DClass:
dc-file resources/phase_3/etc/toon.dc
dc-file resources/phase_3/etc/otp.dc

# Mouse Cursor:
cursor-filename phase_3/etc/toonmono.cur
cursor-hidden #f

# Game-Server:
server-version ttc-alpha-v1.0.0
#game-server 199.101.51.117:7199

# Textures:
textures-power-2 up

want-dev 0
accept-clock-skew 1
accepting-new-friends 1
accepting-non-friend-whispers 0
account-old-auth 0
account-server ''
accum-bits 0
adaptive-lru-max-updates-per-frame 40
adaptive-lru-weight 0.2
afk-timeout 600
ai-detect-messenger-leaks 0
allow-collider-multiple 0
allow-flatten-color 0
allow-greyspacing 0
allow-incomplete-render 1
allow-live-flatten 1
allow-nonpipeline-threads 0
allow-open-chat 0
allow-portal-cull 0
allow-secret-chat 0
allow-unrelated-wrt 1
alpha-bits 0
alpha-scale-via-texture 1
always-discard-device 1
anim-blend-type normalized_linear
aspect-ratio 1.333333
assert-abort 0
async-bind-priority 100
async-load-delay 0
asynchronous-clients 1
audio-active 1
audio-buffering-seconds 3
audio-cache-limit 15
audio-distance-factor 1
audio-doppler-factor 1
audio-drop-off-factor 1
audio-force-midi-reset 1
audio-library-name miles_audio
audio-min-hw-channels 15
audio-music-active 1
audio-output-bits 16
audio-output-channels 2
audio-output-rate 22050
audio-play-midi 1
audio-play-mp3 1
audio-play-wave 1
audio-preload-threshold 1000000
audio-sfx-active 1
audio-software-midi #t
audio-volume 1
auto-break-cycles 1
auto-cpu-data 0
auto-flip 0
auto-play-again 0
auto-single-cpu-affinity 0
aux-display pandadx9
aux-display pandadx8
aux-display pandagl
aux-display tinydisplay
average-frame-rate-interval 1
back-buffers 1
background-color 0.41 0.41 0.41
bam-endian littleendian
bam-texture-mode relative
basic-shaders-only 0
battle-input-timeout 20
battle-sound-cache-size 15
block-country-club-rooms 1
bmp-bpp 0
bounds-type sphere
callback-node-name pPlane*
change-display-api 0
change-display-settings 1
check-language 0
client-cpu-affinity -1
client-cpu-affinity-mask -1
client-detect-leaks 0
client-log-stack-dump 0
client-run-garbage-reports 0
client-sleep 0
clip-plane-cull 1
clock-degrade-factor 1
clock-frame-rate 120
clock-mode limited
cluster-sync 0
cogdo-game-difficulty -1
cogdo-game-safezone-id -1
cogdoflying-dev 0
collect-tcp 1
collect-tcp-interval 0.2
collision-parabola-bounds-sample 10
collision-parabola-bounds-threshold 10
color-bits 0
lor-scale-via-lighting 1
compose-componentwise 1
compress-chan-quality 95
compress-channels #t
compressed-textures 0
connect-method default
connect-triangle-strips 1
console-output 0
coordinate-system zup_right
copy-texture-inverted 0
crash-on-proactive-leak-detect 1
crdatacache-size 10
cull-bin gui-popup 60 unsorted
cull-bin shadow 15 fixed
cull-bin ground 14 fixed
cursor-filename resources/phase_3/etc/toonmono.cur
cursor-hidden 0
dc-multiple-inheritance 1
dc-sort-inheritance-by-file 1
dc-virtual-inheritance 1
debug-portal-cull 0
decompressor-step-time 0.01
default-converge 25
default-directnotify-level info
default-far 100000
default-fov 30
default-iod 0.2
default-keystone 0
default-lod-type pop
default-model-extension .bam
default-near 1
default-stereo-camera 1
default_max_angular_dt 0.0333333
default_max_linear_dt 0.0333333
default_noise_force_seed 665
default_terminal_velocity 400
deferred-generate-interval 0.2
depth-bits 0
depth-offset-decals 0
detect-graph-cycles 1
detect-leaks 0
detect-messenger-leaks 0
direct-gui-edit 0
direct-wtext 1
disable-sticky-keys 0
display-list-animation 0
display-lists 0
do-vidmemsize-check 1
download-throttle 0
downloader-byte-rate 125000
downloader-frequency 0.1
downloader-timeout 15
downloader-timeout-retries 4
drive-forward-speed 20
drive-horizontal-center 0
drive-horizontal-dead-zone 0.1
drive-horizontal-ramp-down-time 0
drive-horizontal-ramp-up-time 0
drive-reverse-speed 10
drive-rotate-speed 80
drive-vertical-center 0
drive-vertical-dead-zone 0.1
drive-vertical-ramp-down-time 0
drive-vertical-ramp-up-time 0
driver-compress-textures 0
driver-generate-mipmaps 0
dump-generated-shaders 0
dx-broken-depth-bias 1
dx-broken-max-index 1
dx-count-all-cards-memory 1
dx-depth-bias-scale 1e-006
dx-disable-driver-management 0
dx-disable-driver-management-ex 0
dx-force-16bpp-zbuffer 0
dx-force-anisotropic-filtering 0
dx-ignore-mipmaps 0
dx-intel-compressed-texture-bug 1
dx-lru-debug 0
dx-lru-debug-frames-til-output 500
dx-lru-debug-textures 0
dx-lru-debug-vertex-buffers 0
dx-lru-free-memory-requirement 12000000
dx-lru-management 1
dx-lru-maximum-memory-requirement 0
dx-lru-maximum-page-updates-per-frame 40
dx-lru-maximum-pages 8192
dx-lru-minimum-memory-requirement 64000000
dx-management 1
dx-mipmap-everything 0
dx-no-dithering 0
dx-no-vertex-fog 0
dx-preferred-device-id -1
dx-preserve-fpu-state 1
dx-show-cursor-watermark 0
dx-show-transforms 0
dx-texture-management 1
dx-use-dynamic-textures 1
dx-use-multithread 0
dx-use-nvperfhud 0
dx-use-puredevice 0
dx-use-rangebased-fog #t
dx-use-triangle-mipgen-filter 0
early-event-sphere 1
early-random-seed 1
empty-node-path future
encryption-algorithm bf-cbc
encryption-iteration-count 100000
encryption-key-length 0
endless-2d-game 0
endless-catch-game 0
endless-maze-game 0
endless-pairing-game 0
endless-ring-game 0
enforce-attrib-lock 1
estate-cannons 0
estate-clouds 0
estate-day-night 0
estate-fireworks 0
estate-goon 0
even-animation 0
exec-chat 0
extended-exceptions 0
extra-ssl-handshake-time 20.0
extractor-step-time 0.01
fake-view-frustum-cull 0
fft-error-threshold  2.0
ft-exponent 4
fft-factor 0.1
fft-offset 0.001
fill-shards-to-ideal-pop 1
flatten-collision-nodes 0
flatten-geoms 1
fluid-cap-amount 100
fmod-number-of-sound-channels 120
fmod-use-surround-sound 0
force-parasite-buffer 0
force-reports 0
frame-rate-meter-layer-sort 1000
frame-rate-meter-scale 0.05
frame-rate-meter-side-margins 0.5
frame-rate-meter-text-pattern %0.1f fps
frame-rate-meter-update-interval 1.5
framebuffer-accum 0
framebuffer-alpha 1
framebuffer-depth 1
framebuffer-hardware 1
framebuffer-multisample 0
framebuffer-software 0
framebuffer-stencil 0
framebuffer-stereo 0
fullscreen False
game-server-timeout-ms 20000
garbage-threshold-adjust-delay 300
gc-save-all 1
geom-cache-min-frames 1
geom-cache-size 5000
golf-power-exponent 0.75
golf-power-speed 3
graphics-memory-limit -1
handle-datagrams-internally 1
hardware-animated-vertices 0
hardware-point-sprites 1
hardware-points 1
heartbeat-interval 10
hold-keys-across-windows 0
http-connect-timeout 20
http-idle-timeout 5
http-max-connect-count 10
http-preapproved-server-certificate-filename toontownclassic.net resources/phase_3/etc/gameserver.txt
http-proxy-tunnel 0
http-skip-body-size 8192
http-timeout 30
http-try-all-direct 1
icon-filename resources/phase_3/etc/toontown.ico
ignore-user-options 0
ime-aware 1
ime-hide 1
img-header-type sort
img-size 0
inactivity-timeout 180
interest-debug 0
interpolate-frames 0
interval-precision 1000
jpeg-quality 95
keep-aspect-ratio 0
keep-temporary-files 0
keep-texture-ram 0
kill-interest-response 0
language english
launcher-bps-window 8
launcher-decrease-bandwidth 1
launcher-decrease-threshold 0.5
launcher-increase-threshold 0.75
launcher-max-bandwidth 0
launcher-telemetry-bandwidth 2000
launcher-user-update-delay 0.5
launcher-verify 0
lens-far-limit 1e-007
level-edit-username UNDEFINED_USERNAME
level-visibility 1
link-tristrips 0
load-file-type toontown
loader-num-threads 1
loader-thread-priority low
lock-to-one-cpu 1
lod-fade-bin-draw-order 0
lod-fade-bin-name fixed
lod-fade-state-override 1000
lod-fade-time 0.5
log-private-info 0
log-stack-dump 0
m-dual 1
m-dual-flash 0
m-dual-opaque 1
m-dual-transparent 1
matrix-palette 0
max-attribs 32
max-collect-indices 65535
max-collect-vertices 65535
max-compressed-vertex-data 0
max-disk-vertex-data -1
max-dt -1
max-independent-vertex-data -1
max-lag 0
max-lenses 100
max-occlusion-vertices 3000
max-resident-vertex-data -1
max-texture-dimension -1
max-texture-stages -1
miles-audio-expand-mp3-threshold 16384
miles-audio-panda-threads 1
miles-audio-preload-threshold -1
min-lag 0
min-occlusion-vertices 300
minigame-difficulty -1
minigame-safezone-id -1
model-cache-compressed-textures 0
model-cache-flush 30
model-cache-max-kbytes 1048576
model-cache-models 1
model-cache-textures 1
multi-sleep 0
multifile-encryption-iteration-count 0
multisamples 0
name-deleted-mutexes 0
nametag-fixed-bin fixed
nametags-visible 1
newline-mode native
news-base-dir /httpNews
news-index-filename http_news_index.txt
news-nonblocking 1
news-over-http 1
news-stage-dir news
news-url /news/news_urls.txt
no-unsupported-copy 0
show-frame-rate-meter True
want-ssl-support False