#define yy_create_buffer eggyy_create_buffer
#define yy_delete_buffer eggyy_delete_buffer
#define yy_scan_buffer eggyy_scan_buffer
#define yy_scan_string eggyy_scan_string
#define yy_scan_bytes eggyy_scan_bytes
#define yy_flex_debug eggyy_flex_debug
#define yy_init_buffer eggyy_init_buffer
#define yy_flush_buffer eggyy_flush_buffer
#define yy_load_buffer_state eggyy_load_buffer_state
#define yy_switch_to_buffer eggyy_switch_to_buffer
#define yyin eggyyin
#define yyleng eggyyleng
#define yylex eggyylex
#define yyout eggyyout
#define yyrestart eggyyrestart
#define yytext eggyytext
#define yywrap eggyywrap

#line 20 "built/tmp/lexer.lxx.cxx"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
                   

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 101
#define YY_END_OF_BUFFER 102
static yyconst short int yy_accept[585] =
    {   0,
        0,    0,  102,  100,    2,    1,   99,  100,  100,  100,
      100,   91,   91,   91,  100,  100,  100,    5,  100,    1,
      100,   91,   91,  100,   91,    4,    3,   91,   93,  100,
       92,   91,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,   91,  100,    3,    3,   93,  100,
       91,   92,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,

      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,   67,  100,  100,
      100,   95,  100,  100,   96,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,   20,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,   82,  100,  100,
      100,  100,  100,  100,  100,  100,    7,  100,  100,  100,

      100,  100,  100,  100,  100,  100,  100,  100,  100,   26,
      100,  100,  100,  100,  100,   24,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,   53,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
       68,  100,  100,  100,  100,  100,  100,  100,  100,   79,
      100,  100,  100,  100,  100,  100,   94,  100,   97,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,   21,  100,  100,  100,  100,  100,   25,  100,   30,
      100,  100,  100,  100,  100,   37,   38,  100,  100,  100,

       43,  100,  100,  100,  100,  100,  100,  100,  100,   54,
      100,   56,   57,   58,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,   75,  100,   78,  100,
      100,  100,  100,  100,  100,   94,   98,  100,  100,    9,
      100,  100,  100,   14,  100,  100,  100,  100,  100,  100,
      100,  100,   23,   28,  100,   31,  100,  100,   33,   34,
      100,  100,   42,  100,  100,  100,  100,   48,  100,   50,
      100,  100,  100,  100,  100,   61,  100,  100,  100,   66,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,   13,   15,  100,

      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,   44,  100,  100,  100,  100,  100,  100,   55,
       59,   60,  100,  100,   64,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,   85,  100,  100,
      100,  100,  100,  100,  100,  100,   16,   17,  100,  100,
      100,  100,   22,  100,   35,  100,  100,   40,   41,  100,
      100,  100,  100,  100,   52,  100,   63,  100,   69,   70,
       71,  100,  100,  100,  100,   80,   81,   83,   84,  100,
      100,  100,  100,  100,  100,  100,   12,  100,  100,  100,
       27,  100,   36,   39,  100,  100,  100,  100,  100,   62,

      100,   72,  100,  100,  100,  100,  100,  100,  100,   89,
      100,  100,  100,   10,  100,   18,  100,  100,  100,  100,
      100,  100,  100,  100,  100,   73,   74,  100,  100,  100,
      100,   88,  100,  100,  100,  100,  100,  100,  100,   45,
      100,   47,   49,   51,  100,  100,  100,   86,   87,  100,
        6,    8,  100,  100,   32,  100,  100,  100,   76,  100,
       90,  100,  100,  100,   46,  100,  100,  100,  100,  100,
      100,   77,  100,  100,  100,  100,   11,  100,  100,   65,
       19,  100,   29,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    6,    1,    1,    1,    1,
        1,    7,    8,    1,    9,   10,   11,   12,   13,   14,
       15,   16,   14,   14,   14,   14,   14,    1,    1,   17,
        1,   18,    1,    1,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
        1,    1,    1,    1,   19,    1,   20,   21,   22,   23,

       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   45,   46,    1,   46,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[47] =
    {   0,
        1,    2,    3,    2,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2
    } ;

static yyconst short int yy_base[590] =
    {   0,
        0,   45,  706,    0,  707,    0,  707,    8,   82,   22,
       18,  101,    9,   20,  125,  672,  684,  707,    0,    0,
       52,   29,   59,  670,   69,    0,   40,  114,   14,  161,
      166,  187,   37,   79,  108,  192,  674,  664,  667,  665,
      665,   11,   86,   65,   50,   54,  107,  191,  197,   99,
      186,  672,  671,  662,  236,  669,  181,    0,   19,  230,
      241,    0,  665,  664,  648,  645,  669,  101,  655,  667,
      652,  162,  667,  647,  645,  657,  643,  646,  653,  641,
      636,  632,  642,  643,  639,   99,  644,  637,  637,  635,
      629,  644,  642,  628,  627,  634,  639,  622,  621,   12,

      634,  637,  618,  636,  635,  618,  633,  624,  237,  608,
      626,  202,  610,  618,  617,  628,  615,    0,  614,  606,
      610,    0,  629,  612,    0,  606,  606,  619,  608,  613,
      603,  599,  609,  594,  592,  598,   44,  591,    0,  588,
      608,  605,  585,  586,  601,  597,  602,  574,  598,  593,
      576,  584,  575,  580,  573,  587,  575,  147,  585,  583,
      575,  585,  581,  580,  564,  580,  568,  556,  581,  578,
      239,  564,  565,  555,  571,  554,  561,  573,  564,   70,
      556,  555,  562,   80,  568,  552,  551,    0,  550,  549,
      542,  574,  536,  545,  552,  541,    0,  551,  550,  552,

      535,  540,  563,  545,  540,  543,  532,  542,  546,    0,
      523,  542,  529,  540,  534,    0,  540,  525,  538,  520,
      514,  533,  513,  513,  532,  531,  511,  519,  515,  527,
      524,  505,  520,  504,  520,  512,  499,  511,    0,  518,
      496,  516,  515,  514,  503,  199,  506,  501,  506,  503,
        0,  502,  497,  484,  497,  484,  503,  487,  501,    0,
      484,  483,  482,  481,  490,  493,  273,  487,    0,  474,
      473,  491,  474,  475,  482,  487,  481,  480,  469,  468,
      472,    0,  468,  465,  477,  478,  477,    0,  466,    0,
      475,  469,  458,  472,  471,    0,    0,  460,  444,  468,

        0,  454,  114,  445,  465,  449,  463,  449,  445,    0,
      454,    0,    0,    0,  445,  439,  457,  441,  440,  445,
      453,  437,  431,  431,  428,  136,    0,  440,    0,  426,
      425,  424,  423,  418,  427,    0,    0,  435,  436,    0,
      437,  436,  437,    0,  436,  429,  413,  427,  417,  410,
      426,  416,    0,    0,  424,    0,  421,  422,    0,    0,
      423,  191,    0,  424,  401,  400,  400,    0,  412,    0,
      409,  403,  417,  416,  415,    0,  410,  405,  243,    0,
      391,  390,  404,  400,  392,  405,  393,  385,  384,  383,
      382,  244,  391,  387,  377,  379,  384,    0,    0,  396,

      395,  379,  391,  375,  385,  390,  366,  388,  381,  373,
      385,  384,    0,  364,  363,  355,  374,  371,  378,    0,
        0,    0,  371,  376,    0,  359,  374,  373,  372,  351,
      351,  348,  362,  367,  366,  365,  364,    0,  348,  346,
      355,  346,  343,  339,  352,  356,    0,    0,  334,  333,
      337,  352,    0,  345,    0,  350,  349,    0,    0,  325,
      340,  329,  330,  335,    0,  343,    0,  327,    0,    0,
        0,  341,  326,  333,  199,    0,    0,    0,    0,  328,
      321,  329,  190,  333,  311,  249,    0,  333,  326,  311,
        0,  311,    0,    0,  323,  326,  321,  305,  304,    0,

      319,    0,  323,  322,  319,  299,  305,  305,  317,    0,
      296,  310,  308,    0,  307,    0,  292,  305,  289,  309,
      304,  307,  306,  305,  294,    0,    0,  288,  283,  301,
      300,    0,  311,  298,  297,  281,  269,  294,  287,    0,
      286,    0,    0,    0,  270,  290,  264,    0,    0,  273,
        0,    0,  251,  242,    0,  235,  259,  248,    0,  240,
        0,  250,  234,  237,    0,  235,  250,  229,  223,  205,
      205,    0,  180,  140,  109,  106,    0,   71,   44,    0,
        0,   33,    0,  707,  298,    0,  301,  303,  305
    } ;

static yyconst short int yy_def[590] =
    {   0,
      585,  585,  584,  586,  584,  587,  584,  586,  586,  586,
      586,  586,   12,   12,  586,  586,  586,  584,  586,  587,
      586,   12,   12,  586,  586,  586,  588,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  588,  589,  586,  586,
      586,   31,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,

      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,

      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,

      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  267,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,

      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,

      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,    0,  584,  584,  584,  584,  584
    } ;

static yyconst short int yy_nxt[754] =
    {   0,
       19,    5,    6,    7,  584,  584,  584,    8,    9,   10,
       11,   12,   13,   14,   14,   14,   15,   21,   32,   22,
       22,   22,   22,   22,   26,   59,   59,   16,   27,   19,
       59,   59,   17,   25,   25,   25,   25,   25,   89,  167,
       19,   58,  168,   58,   90,   18,    5,    6,    7,   19,
      583,   19,    8,    9,   10,   11,   12,   13,   14,   14,
       14,   15,   19,   25,   25,   25,   25,   25,   55,   64,
       96,   19,   16,   99,  582,  206,   65,   17,  207,   19,
       25,   25,   25,   25,   25,   58,   97,  100,  581,   98,
       18,   21,   30,   22,   23,   22,   22,   22,   94,  258,

      253,   19,   66,   67,   95,   91,   68,  114,  254,   24,
       28,  259,   22,   22,   22,   22,   22,  115,   69,   92,
      152,   29,   93,  580,   30,   25,   25,   25,   25,   25,
      101,  131,  102,  132,   70,  365,  153,   30,   71,  116,
      103,   72,  579,   31,   33,   34,   35,   36,   73,   37,
       38,  366,   39,   40,   41,   42,   43,   44,   45,   46,
      385,   47,   48,   49,   50,   51,  386,   52,   60,   60,
      227,  578,   61,   61,   61,   61,   61,   62,   62,   62,
       62,   62,   58,  228,   58,   62,   62,   62,   62,   62,
       62,   63,  136,  137,  117,  138,  104,  577,   25,   25,

       25,   25,   25,  118,  119,  411,  412,  510,  511,  120,
       30,   74,  105,   75,  106,   76,  109,  107,  316,   77,
      110,  182,  317,  505,   78,  183,   58,  111,   79,  184,
       80,   81,  108,  112,   82,   83,  506,  576,  575,  113,
      124,   61,   61,   61,   61,   61,  574,   25,   25,   25,
       25,   25,   61,   61,   61,   61,   61,  177,  241,   30,
      425,  438,  178,  439,  426,  573,  514,  572,  571,  179,
      515,  570,  569,  568,  567,  566,  565,  564,  440,  563,
      441,  242,  243,  244,  336,  336,  336,  336,  336,  562,
      561,  560,  336,  336,  336,  336,  336,  336,    4,    4,

        4,   20,   20,   57,   57,   58,   58,  559,  558,  557,
      556,  555,  554,  553,  552,  551,  550,  549,  548,  547,
      546,  545,  544,  543,  542,  541,  540,  539,  538,  537,
      536,  535,  534,  533,  532,  531,  530,  529,  528,  527,
      526,  525,  524,  523,  522,  521,  520,  519,  518,  517,
      516,  513,  512,  509,  508,  507,  504,  503,  502,  501,
      500,  499,  498,  497,  496,  495,  494,  493,  492,  491,
      490,  489,  488,  487,  486,  485,  484,  483,  482,  481,
      480,  479,  478,  477,  476,  475,  474,  473,  472,  471,
      470,  469,  468,  467,  466,  465,  464,  463,  462,  461,

      460,  459,  458,  457,  456,  455,  454,  453,  452,  451,
      450,  449,  448,  447,  446,  445,  444,  443,  442,  437,
      436,  435,  434,  433,  432,  431,  430,  429,  428,  427,
      424,  423,  422,  421,  420,  419,  418,  417,  416,  415,
      414,  413,  410,  409,  408,  407,  406,  405,  404,  403,
      402,  401,  400,  399,  398,  397,  396,  395,  394,  393,
      392,  391,  390,  389,  388,  387,  384,  383,  382,  381,
      380,  379,  378,  377,  376,  375,  374,  373,  372,  371,
      370,  369,  368,  367,  364,  363,  362,  361,  360,  359,
      358,  357,  356,  355,  354,  353,  352,  351,  350,  349,

      348,  347,  346,  345,  344,  343,  342,  341,  340,  339,
      338,  337,  335,  334,  333,  332,  331,  330,  329,  328,
      327,  326,  325,  324,  323,  322,  321,  320,  319,  318,
      315,  314,  313,  312,  311,  310,  309,  308,  307,  306,
      305,  304,  303,  302,  301,  300,  299,  298,  297,  296,
      295,  294,  293,  292,  291,  290,  289,  288,  287,  286,
      285,  284,  283,  282,  281,  280,  279,  278,  277,  276,
      275,  274,  273,  272,  271,  270,  269,  268,  267,  266,
      265,  264,  263,  262,  261,  260,  257,  256,  255,  252,
      251,  250,  249,  248,  247,  246,  245,  240,  239,  238,

      237,  236,  235,  234,  233,  232,  231,  230,  229,  226,
      225,  224,  223,  222,  221,  220,  219,  218,  217,  216,
      215,  214,  213,  212,  211,  210,  209,  208,  205,  204,
      203,  202,  201,  200,  199,  198,  197,  196,  195,  194,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  181,
      180,  176,  175,  174,  173,  172,  171,  170,  169,  166,
      165,  164,  163,  162,  161,  160,  159,  158,  157,  156,
      155,  154,  151,  150,  149,  148,  147,  146,  145,  144,
      143,  142,  141,  140,  139,  135,  134,  133,  130,  129,
      128,  127,  126,  125,  123,  122,  121,   88,   87,   86,

       85,   84,   56,   54,   53,  584,    3,  584,  584,  584,
      584,  584,  584,  584,  584,  584,  584,  584,  584,  584,
      584,  584,  584,  584,  584,  584,  584,  584,  584,  584,
      584,  584,  584,  584,  584,  584,  584,  584,  584,  584,
      584,  584,  584,  584,  584,  584,  584,  584,  584,  584,
      584,  584,  584
    } ;

static yyconst short int yy_chk[754] =
    {   0,
      586,    1,    1,    1,    0,    0,    0,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    8,   13,    8,
        8,    8,    8,    8,   11,   29,   29,    1,   11,   13,
       59,   59,    1,   10,   10,   10,   10,   10,   42,  100,
       14,   27,  100,   27,   42,    1,    2,    2,    2,   22,
      582,   13,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,   14,   21,   21,   21,   21,   21,   23,   33,
       45,   22,    2,   46,  579,  137,   33,    2,  137,   23,
       25,   25,   25,   25,   25,   27,   45,   46,  578,   45,
        2,    9,   25,    9,    9,    9,    9,    9,   44,  184,

      180,   23,   34,   34,   44,   43,   34,   50,  180,    9,
       12,  184,   12,   12,   12,   12,   12,   50,   34,   43,
       86,   12,   43,  576,   12,   28,   28,   28,   28,   28,
       47,   68,   47,   68,   35,  303,   86,   28,   35,   50,
       47,   35,  575,   12,   15,   15,   15,   15,   35,   15,
       15,  303,   15,   15,   15,   15,   15,   15,   15,   15,
      326,   15,   15,   15,   15,   15,  326,   15,   30,   30,
      158,  574,   30,   30,   30,   30,   30,   31,   31,   31,
       31,   31,   57,  158,   57,   31,   31,   31,   31,   31,
       31,   32,   72,   72,   51,   72,   48,  573,   32,   32,

       32,   32,   32,   51,   51,  362,  362,  483,  483,   51,
       32,   36,   48,   36,   48,   36,   49,   48,  246,   36,
       49,  112,  246,  475,   36,  112,   57,   49,   36,  112,
       36,   36,   48,   49,   36,   36,  475,  571,  570,   49,
       55,   60,   60,   60,   60,   60,  569,   55,   55,   55,
       55,   55,   61,   61,   61,   61,   61,  109,  171,   55,
      379,  392,  109,  392,  379,  568,  486,  567,  566,  109,
      486,  564,  563,  562,  560,  558,  557,  556,  392,  554,
      392,  171,  171,  171,  267,  267,  267,  267,  267,  553,
      550,  547,  267,  267,  267,  267,  267,  267,  585,  585,

      585,  587,  587,  588,  588,  589,  589,  546,  545,  541,
      539,  538,  537,  536,  535,  534,  533,  531,  530,  529,
      528,  525,  524,  523,  522,  521,  520,  519,  518,  517,
      515,  513,  512,  511,  509,  508,  507,  506,  505,  504,
      503,  501,  499,  498,  497,  496,  495,  492,  490,  489,
      488,  485,  484,  482,  481,  480,  474,  473,  472,  468,
      466,  464,  463,  462,  461,  460,  457,  456,  454,  452,
      451,  450,  449,  446,  445,  444,  443,  442,  441,  440,
      439,  437,  436,  435,  434,  433,  432,  431,  430,  429,
      428,  427,  426,  424,  423,  419,  418,  417,  416,  415,

      414,  412,  411,  410,  409,  408,  407,  406,  405,  404,
      403,  402,  401,  400,  397,  396,  395,  394,  393,  391,
      390,  389,  388,  387,  386,  385,  384,  383,  382,  381,
      378,  377,  375,  374,  373,  372,  371,  369,  367,  366,
      365,  364,  361,  358,  357,  355,  352,  351,  350,  349,
      348,  347,  346,  345,  343,  342,  341,  339,  338,  335,
      334,  333,  332,  331,  330,  328,  325,  324,  323,  322,
      321,  320,  319,  318,  317,  316,  315,  311,  309,  308,
      307,  306,  305,  304,  302,  300,  299,  298,  295,  294,
      293,  292,  291,  289,  287,  286,  285,  284,  283,  281,

      280,  279,  278,  277,  276,  275,  274,  273,  272,  271,
      270,  268,  266,  265,  264,  263,  262,  261,  259,  258,
      257,  256,  255,  254,  253,  252,  250,  249,  248,  247,
      245,  244,  243,  242,  241,  240,  238,  237,  236,  235,
      234,  233,  232,  231,  230,  229,  228,  227,  226,  225,
      224,  223,  222,  221,  220,  219,  218,  217,  215,  214,
      213,  212,  211,  209,  208,  207,  206,  205,  204,  203,
      202,  201,  200,  199,  198,  196,  195,  194,  193,  192,
      191,  190,  189,  187,  186,  185,  183,  182,  181,  179,
      178,  177,  176,  175,  174,  173,  172,  170,  169,  168,

      167,  166,  165,  164,  163,  162,  161,  160,  159,  157,
      156,  155,  154,  153,  152,  151,  150,  149,  148,  147,
      146,  145,  144,  143,  142,  141,  140,  138,  136,  135,
      134,  133,  132,  131,  130,  129,  128,  127,  126,  124,
      123,  121,  120,  119,  117,  116,  115,  114,  113,  111,
      110,  108,  107,  106,  105,  104,  103,  102,  101,   99,
       98,   97,   96,   95,   94,   93,   92,   91,   90,   89,
       88,   87,   85,   84,   83,   82,   81,   80,   79,   78,
       77,   76,   75,   74,   73,   71,   70,   69,   67,   66,
       65,   64,   63,   56,   54,   53,   52,   41,   40,   39,

       38,   37,   24,   17,   16,    3,  584,  584,  584,  584,
      584,  584,  584,  584,  584,  584,  584,  584,  584,  584,
      584,  584,  584,  584,  584,  584,  584,  584,  584,  584,
      584,  584,  584,  584,  584,  584,  584,  584,  584,  584,
      584,  584,  584,  584,  584,  584,  584,  584,  584,  584,
      584,  584,  584
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "panda/src/egg/lexer.lxx"
#define INITIAL 0
/**
 * @file lexer.lxx
 * @author drose
 * @date 1999-01-16
 */
#line 8 "panda/src/egg/lexer.lxx"
#include "pandabase.h"
#include "lexerDefs.h"
#include "parserDefs.h"
#include "config_egg.h"
#include "parser.h"
#include "indent.h"
#include "pnotify.h"
#include "lightMutex.h"
#include "thread.h"
#include "pstrtod.h"

#include <math.h>

extern "C" int eggyywrap(void);  // declared below.

static int yyinput(void);        // declared by flex.


////////////////////////////////////////////////////////////////////
// Static variables
////////////////////////////////////////////////////////////////////

// This mutex protects all of these global variables.
LightMutex egg_lock;

// We'll increment line_number and col_number as we parse the file, so
// that we can report the position of an error.
static int line_number = 0;
static int col_number = 0;

// current_line holds as much of the current line as will fit.  Its
// only purpose is for printing it out to report an error to the user.
static const int max_error_width = 1024;
static char current_line[max_error_width + 1];

static int error_count = 0;
static int warning_count = 0;

// This is the pointer to the current input stream.
static istream *input_p = NULL;

// This is the name of the egg file we're parsing.  We keep it so we
// can print it out for error messages.
static string egg_filename;

// This is the initial token state returned by the lexer.  It allows
// the yacc grammar to start from initial points.
static int initial_token;

////////////////////////////////////////////////////////////////////
// Defining the interface to the lexer.
////////////////////////////////////////////////////////////////////

void
egg_init_lexer(istream &in, const string &filename) {
  input_p = &in;
  egg_filename = filename;
  line_number = 0;
  col_number = 0;
  error_count = 0;
  warning_count = 0;
  initial_token = START_EGG;
}

void
egg_start_group_body() {
  /* Set the initial state to begin within a group_body context,
     instead of at the beginning of the egg file. */
  initial_token = START_GROUP_BODY;
}

void
egg_start_texture_body() {
  initial_token = START_TEXTURE_BODY;
}

void
egg_start_primitive_body() {
  initial_token = START_PRIMITIVE_BODY;
}

int
egg_error_count() {
  return error_count;
}

int
egg_warning_count() {
  return warning_count;
}


////////////////////////////////////////////////////////////////////
// Internal support functions.
////////////////////////////////////////////////////////////////////

int
eggyywrap(void) {
  return 1;
}

void
eggyyerror(const string &msg) {
  if (egg_cat.is_error()) {
    ostream &out = egg_cat.error(false);

    out << "\nError";
    if (!egg_filename.empty()) {
      out << " in " << egg_filename;
    }
    out
      << " at line " << line_number << ", column " << col_number << ":\n"
      << setiosflags(Notify::get_literal_flag())
      << current_line << "\n";
    indent(out, col_number-1)
      << "^\n" << msg << "\n\n"
      << resetiosflags(Notify::get_literal_flag()) << flush;
  }
  error_count++;
}

void
eggyyerror(ostringstream &strm) {
  string s = strm.str();
  eggyyerror(s);
}

void
eggyywarning(const string &msg) {
  if (egg_cat.is_warning()) {
    ostream &out = egg_cat.warning(false);

    out << "\nWarning";
    if (!egg_filename.empty()) {
      out << " in " << egg_filename;
    }
    out
      << " at line " << line_number << ", column " << col_number << ":\n"
      << setiosflags(Notify::get_literal_flag())
      << current_line << "\n";
    indent(out, col_number-1)
      << "^\n" << msg << "\n\n"
      << resetiosflags(Notify::get_literal_flag()) << flush;
  }
  warning_count++;
}

void
eggyywarning(ostringstream &strm) {
  string s = strm.str();
  eggyywarning(s);
}

// Now define a function to take input from an istream instead of a
// stdio FILE pointer.  This is flex-specific.
static void
input_chars(char *buffer, int &result, int max_size) {
  nassertv(input_p != NULL);
  if (*input_p) {
    input_p->read(buffer, max_size);
    result = input_p->gcount();

    if (line_number == 0) {
      // This is a special case.  If we are reading the very first bit
      // from the stream, copy it into the current_line array.  This
      // is because the \n.* rule below, which fills current_line
      // normally, doesn't catch the first line.
      int length = min(max_error_width, result);
      strncpy(current_line, buffer, length);
      current_line[length] = '\0';
      line_number++;
      col_number = 0;

      // Truncate it at the newline.
      char *end = strchr(current_line, '\n');
      if (end != NULL) {
        *end = '\0';
      }
    }

  } else {
    // End of file or I/O error.
    result = 0;
  }
  Thread::consider_yield();
}
#undef YY_INPUT

// Define this macro carefully, since different flex versions call it
// with a different type for result.
#define YY_INPUT(buffer, result, max_size) { \
  int int_result; \
  input_chars((buffer), int_result, (max_size)); \
  (result) = int_result; \
}

// read_char reads and returns a single character, incrementing the
// supplied line and column numbers as appropriate.  A convenience
// function for the scanning functions below.
static int
read_char(int &line, int &col) {
  int c = yyinput();
  if (c == '\n') {
    line++;
    col = 0;
  } else {
    col++;
  }
  return c;
}

// scan_quoted_string reads a string delimited by quotation marks and
// returns it.
static string
scan_quoted_string() {
  string result;

  // We don't touch the current line number and column number during
  // scanning, so that if we detect an error while scanning the string
  // (e.g. an unterminated string), we'll report the error as
  // occurring at the start of the string, not at the end--somewhat
  // more convenient for the user.

  // Instead of adjusting the global line_number and col_number
  // variables, we'll operate on our own local variables for the
  // interim.
  int line = line_number;
  int col = col_number;

  int c;
  c = read_char(line, col);
  while (c != '"' && c != EOF) {
    result += c;
    c = read_char(line, col);
  }

  if (c == EOF) {
    eggyyerror("This quotation mark is unterminated.");
  }

  line_number = line;
  col_number = col;

  return result;
}

// eat_c_comment scans past all characters up until the first */
// encountered.
static void
eat_c_comment() {
  // As above, we'll operate on our own local copies of line_number
  // and col_number within this function.

  int line = line_number;
  int col = col_number;

  int c, last_c;

  last_c = '\0';
  c = read_char(line, col);
  while (c != EOF && !(last_c == '*' && c == '/')) {
    if (last_c == '/' && c == '*') {
      ostringstream errmsg;
      errmsg << "This comment contains a nested /* symbol at line "
             << line << ", column " << col-1 << "--possibly unclosed?"
             << ends;
      eggyywarning(errmsg);
    }
    last_c = c;
    c = read_char(line, col);
  }

  if (c == EOF) {
    eggyyerror("This comment marker is unclosed.");
  }

  line_number = line;
  col_number = col;
}


// accept() is called below as each piece is pulled off and
// accepted by the lexer; it increments the current column number.
INLINE void accept() {
  col_number += yyleng;
}

#line 1030 "built/tmp/lexer.lxx.cxx"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 301 "panda/src/egg/lexer.lxx"



  if (initial_token != 0) {
    int t = initial_token;
    initial_token = 0;
    return t;
  }


#line 1188 "built/tmp/lexer.lxx.cxx"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 585 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 707 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 311 "panda/src/egg/lexer.lxx"
{
  // New line.  Save a copy of the line so we can print it out for the
  // benefit of the user in case we get an error.

  strncpy(current_line, yytext+1, max_error_width);
  current_line[max_error_width] = '\0';
  line_number++;
  col_number=0;

  // Return the whole line to the lexer, except the newline character,
  // which we eat.
  yyless(1);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 325 "panda/src/egg/lexer.lxx"
{
  // Eat whitespace.
  accept();
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 330 "panda/src/egg/lexer.lxx"
{
  // Eat C++-style comments.
  accept();
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 335 "panda/src/egg/lexer.lxx"
{
  // Eat C-style comments.
  accept();
  eat_c_comment();
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 341 "panda/src/egg/lexer.lxx"
{
  // Send curly braces as themselves.
  accept();
  return eggyytext[0];
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 349 "panda/src/egg/lexer.lxx"
{
  accept();
  return ANIMPRELOAD;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 353 "panda/src/egg/lexer.lxx"
{
  accept();
  return AUX;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 357 "panda/src/egg/lexer.lxx"
{
  accept();
  return BEZIERCURVE;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 361 "panda/src/egg/lexer.lxx"
{
  accept();
  return BFACE;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 365 "panda/src/egg/lexer.lxx"
{
  accept();
  return BILLBOARD;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 369 "panda/src/egg/lexer.lxx"
{
  accept();
  return BILLBOARDCENTER;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 373 "panda/src/egg/lexer.lxx"
{
  accept();
  return BINORMAL;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 377 "panda/src/egg/lexer.lxx"
{
  accept();
  return BUNDLE;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 381 "panda/src/egg/lexer.lxx"
{
  accept();
  return SCALAR;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 385 "panda/src/egg/lexer.lxx"
{
  accept();
  return CLOSED;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 389 "panda/src/egg/lexer.lxx"
{
  accept();
  return COLLIDE;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 393 "panda/src/egg/lexer.lxx"
{
  accept();
  return COMMENT;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 397 "panda/src/egg/lexer.lxx"
{
  accept();
  return COMPONENT;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 401 "panda/src/egg/lexer.lxx"
{
  accept();
  return COORDSYSTEM;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 405 "panda/src/egg/lexer.lxx"
{
  accept();
  return CV;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 409 "panda/src/egg/lexer.lxx"
{
  accept();
  return DART;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 413 "panda/src/egg/lexer.lxx"
{
  accept();
  return DNORMAL;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 417 "panda/src/egg/lexer.lxx"
{
  accept();
  return DRGBA;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 421 "panda/src/egg/lexer.lxx"
{
  accept();
  return DUV;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 425 "panda/src/egg/lexer.lxx"
{
  accept();
  return DXYZ;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 429 "panda/src/egg/lexer.lxx"
{
  accept();
  return DCS;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 433 "panda/src/egg/lexer.lxx"
{
  accept();
  return DISTANCE;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 437 "panda/src/egg/lexer.lxx"
{
  accept();
  return DTREF;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 441 "panda/src/egg/lexer.lxx"
{
  accept();
  return DYNAMICVERTEXPOOL;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 445 "panda/src/egg/lexer.lxx"
{
  accept();
  return EXTERNAL_FILE;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 449 "panda/src/egg/lexer.lxx"
{
  accept();
  return GROUP;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 453 "panda/src/egg/lexer.lxx"
{
  accept();
  return DEFAULTPOSE;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 457 "panda/src/egg/lexer.lxx"
{
  accept();
  return JOINT;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 461 "panda/src/egg/lexer.lxx"
{
  accept();
  return KNOTS;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 465 "panda/src/egg/lexer.lxx"
{
  accept();
  return INCLUDE;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 469 "panda/src/egg/lexer.lxx"
{
  accept();
  return INSTANCE;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 473 "panda/src/egg/lexer.lxx"
{
  accept();
  return LINE;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 477 "panda/src/egg/lexer.lxx"
{
  accept();
  return LOOP;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 481 "panda/src/egg/lexer.lxx"
{
  accept();
  return MATERIAL;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 485 "panda/src/egg/lexer.lxx"
{
  accept();
  return MATRIX3;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 489 "panda/src/egg/lexer.lxx"
{
  accept();
  return MATRIX4;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 493 "panda/src/egg/lexer.lxx"
{
  accept();
  return MODEL;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 497 "panda/src/egg/lexer.lxx"
{
  accept();
  return MREF;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 501 "panda/src/egg/lexer.lxx"
{
  accept();
  return NORMAL;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 505 "panda/src/egg/lexer.lxx"
{
  accept();
  return NURBSCURVE;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 509 "panda/src/egg/lexer.lxx"
{
  accept();
  return NURBSSURFACE;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 513 "panda/src/egg/lexer.lxx"
{
  accept();
  return OBJECTTYPE;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 517 "panda/src/egg/lexer.lxx"
{
  accept();
  return ORDER;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 521 "panda/src/egg/lexer.lxx"
{
  accept();
  return OUTTANGENT;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 525 "panda/src/egg/lexer.lxx"
{
  accept();
  return PATCH;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 529 "panda/src/egg/lexer.lxx"
{
  accept();
  return POINTLIGHT;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 533 "panda/src/egg/lexer.lxx"
{
  accept();
  return POLYGON;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 537 "panda/src/egg/lexer.lxx"
{
  accept();
  return REF;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 541 "panda/src/egg/lexer.lxx"
{
  accept();
  return RGBA;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 545 "panda/src/egg/lexer.lxx"
{
  accept();
  return ROTATE;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 549 "panda/src/egg/lexer.lxx"
{
  accept();
  return ROTX;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 553 "panda/src/egg/lexer.lxx"
{
  accept();
  return ROTY;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 557 "panda/src/egg/lexer.lxx"
{
  accept();
  return ROTZ;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 561 "panda/src/egg/lexer.lxx"
{
  accept();
  return SANIM;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 565 "panda/src/egg/lexer.lxx"
{
  accept();
  return SCALAR;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 569 "panda/src/egg/lexer.lxx"
{
  accept();
  return SCALE;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 573 "panda/src/egg/lexer.lxx"
{
  accept();
  return SEQUENCE;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 577 "panda/src/egg/lexer.lxx"
{
  accept();
  return SHADING;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 581 "panda/src/egg/lexer.lxx"
{
  accept();
  return SWITCH;
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 585 "panda/src/egg/lexer.lxx"
{
  accept();
  return SWITCHCONDITION;
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 589 "panda/src/egg/lexer.lxx"
{
  accept();
  return TABLE;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 593 "panda/src/egg/lexer.lxx"
{
  accept();
  return TABLE_V;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 597 "panda/src/egg/lexer.lxx"
{
  accept();
  return TAG;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 601 "panda/src/egg/lexer.lxx"
{
  accept();
  return TANGENT;
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 605 "panda/src/egg/lexer.lxx"
{
  accept();
  return TEXLIST;
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 609 "panda/src/egg/lexer.lxx"
{
  accept();
  return TEXTURE;
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 613 "panda/src/egg/lexer.lxx"
{
  accept();
  return TLENGTHS;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 617 "panda/src/egg/lexer.lxx"
{
  accept();
  return TRANSFORM;
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 621 "panda/src/egg/lexer.lxx"
{
  accept();
  return TRANSLATE;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 625 "panda/src/egg/lexer.lxx"
{
  accept();
  return TREF;
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 629 "panda/src/egg/lexer.lxx"
{
  accept();
  return TRIANGLEFAN;
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 633 "panda/src/egg/lexer.lxx"
{
  accept();
  return TRIANGLESTRIP;
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 637 "panda/src/egg/lexer.lxx"
{
  accept();
  return TRIM;
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 641 "panda/src/egg/lexer.lxx"
{
  accept();
  return TXT;
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 645 "panda/src/egg/lexer.lxx"
{
  accept();
  return UKNOTS;
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 649 "panda/src/egg/lexer.lxx"
{
  accept();
  return UKNOTS;
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 653 "panda/src/egg/lexer.lxx"
{
  accept();
  return UV;
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 657 "panda/src/egg/lexer.lxx"
{
  accept();
  return VKNOTS;
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 661 "panda/src/egg/lexer.lxx"
{
  accept();
  return VKNOTS;
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 665 "panda/src/egg/lexer.lxx"
{
  accept();
  return VERTEX;
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 669 "panda/src/egg/lexer.lxx"
{
  accept();
  return VERTEXANIM;
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 673 "panda/src/egg/lexer.lxx"
{
  accept();
  return VERTEXPOOL;
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 677 "panda/src/egg/lexer.lxx"
{
  accept();
  return VERTEXREF;
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 681 "panda/src/egg/lexer.lxx"
{
  accept();
  return XFMANIM;
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 685 "panda/src/egg/lexer.lxx"
{
  accept();
  return XFMSANIM;
}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 692 "panda/src/egg/lexer.lxx"
{
  // An integer or floating-point number.
  accept();
  eggyylval._number = patof(eggyytext);
  eggyylval._string = yytext;
  return EGG_NUMBER;
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 700 "panda/src/egg/lexer.lxx"
{
  // A hexadecimal integer number.
  accept();
  eggyylval._ulong = strtoul(yytext+2, NULL, 16);
  eggyylval._string = yytext;
  return EGG_ULONG;
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 708 "panda/src/egg/lexer.lxx"
{
  // A binary integer number.
  accept();
  eggyylval._ulong = strtoul(yytext+2, NULL, 2);
  eggyylval._string = yytext;
  return EGG_ULONG;
}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 716 "panda/src/egg/lexer.lxx"
{
  // not-a-number.  These sometimes show up in egg files accidentally.
  accept();
  memset(&eggyylval._number, 0, sizeof(eggyylval._number));
  *(unsigned long *)&eggyylval._number = strtoul(yytext+3, NULL, 0);
  eggyylval._string = yytext;
  return EGG_NUMBER;
}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 725 "panda/src/egg/lexer.lxx"
{
  // infinity.  As above.
  accept();
  eggyylval._number = HUGE_VAL;
  eggyylval._string = yytext;
  return EGG_NUMBER;
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 733 "panda/src/egg/lexer.lxx"
{
  // minus infinity.  As above.
  accept();
  eggyylval._number = -HUGE_VAL;
  eggyylval._string = yytext;
  return EGG_NUMBER;
}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 741 "panda/src/egg/lexer.lxx"
{
  // infinity, on Win32.  As above.
  accept();
  eggyylval._number = HUGE_VAL;
  eggyylval._string = yytext;
  return EGG_NUMBER;
}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 749 "panda/src/egg/lexer.lxx"
{
  // minus infinity, on Win32.  As above.
  accept();
  eggyylval._number = -HUGE_VAL;
  eggyylval._string = yytext;
  return EGG_NUMBER;
}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 758 "panda/src/egg/lexer.lxx"
{
  // Quoted string.
  accept();
  eggyylval._string = scan_quoted_string();
  return EGG_STRING;
}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 765 "panda/src/egg/lexer.lxx"
{
  // Unquoted string.
  accept();
  eggyylval._string = yytext;
  return EGG_STRING;
}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 771 "panda/src/egg/lexer.lxx"
ECHO;
	YY_BREAK
#line 2116 "built/tmp/lexer.lxx.cxx"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 585 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 585 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 584);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 771 "panda/src/egg/lexer.lxx"
