/*
 * This file was generated by:
 * built\bin\interrogate -v -srcdir direct/src/showbase -Idirect/src/showbase -DCPPPARSER -D__STDC__=1 -D__cplusplus=201103L -DWIN32_VC -DWIN32 -D_WIN32 -D_M_IX86 -D_MSC_VER=1600 -D__declspec(param)= -D__cdecl -D_near -D_far -D__near -D__far -D__stdcall -oc built/tmp/libp3showbase_igate.cxx -od built/pandac/input/libp3showbase.in -fnames -string -refcount -assert -python-native -Sbuilt/include/parser-inc -Idirect/src/showbase -Sbuilt/tmp -Sbuilt/include -Sthirdparty/win-python/include -Sthirdparty/win-libs-vc10/extras/include -module panda3d.direct -library libp3showbase showBase.cxx showBase.h 
 *
 */

#include "dtoolbase.h"
#include "interrogate_request.h"
#include "dconfig.h"
#include "pnotify.h"
#include <sstream>
#define PANDA_LIBRARY_NAME_libp3showbase
#include "py_panda.h"
#include "extension.h"
#include "dcast.h"

#include "camera.h"
#include "graphicsPipeSelection.h"
#include "graphicsWindow.h"
#include "renderBuffer.h"
#include "showBase.h"
#include "throw_event.h"

#undef _POSIX_C_SOURCE
#undef _XOPEN_SOURCE
#define PY_SSIZE_T_CLEAN 1

#if PYTHON_FRAMEWORK
  #include <Python/Python.h>
#else
  #include "Python.h"
#endif

/**
 * Extern declarations for imported classes
 */
// DConfig
#ifndef LINK_ALL_STATIC
static struct Dtool_PyTypedObject *Dtool_Ptr_DConfig;
#else
extern struct Dtool_PyTypedObject Dtool_DConfig;
static struct Dtool_PyTypedObject *const Dtool_Ptr_DConfig = &Dtool_DConfig;
#endif
// ConfigVariableSearchPath
#ifndef LINK_ALL_STATIC
static struct Dtool_PyTypedObject *Dtool_Ptr_ConfigVariableSearchPath;
inline static bool Dtool_ConstCoerce_ConfigVariableSearchPath(PyObject *args, ConfigVariableSearchPath const *&coerced, bool &manage) {
  nassertr(Dtool_Ptr_ConfigVariableSearchPath != NULL, false);
  nassertr(Dtool_Ptr_ConfigVariableSearchPath->_Dtool_ConstCoerce != NULL, false);
  return ((bool (*)(PyObject *, ConfigVariableSearchPath const *&, bool&))Dtool_Ptr_ConfigVariableSearchPath->_Dtool_ConstCoerce)(args, coerced, manage);
}
inline static bool Dtool_Coerce_ConfigVariableSearchPath(PyObject *args, ConfigVariableSearchPath *&coerced, bool &manage) {
  nassertr(Dtool_Ptr_ConfigVariableSearchPath != NULL, false);
  nassertr(Dtool_Ptr_ConfigVariableSearchPath->_Dtool_Coerce != NULL, false);
  return ((bool (*)(PyObject *, ConfigVariableSearchPath *&, bool&))Dtool_Ptr_ConfigVariableSearchPath->_Dtool_Coerce)(args, coerced, manage);
}
#else
extern struct Dtool_PyTypedObject Dtool_ConfigVariableSearchPath;
static struct Dtool_PyTypedObject *const Dtool_Ptr_ConfigVariableSearchPath = &Dtool_ConfigVariableSearchPath;
extern bool Dtool_ConstCoerce_ConfigVariableSearchPath(PyObject *args, ConfigVariableSearchPath const *&coerced, bool &manage);
extern bool Dtool_Coerce_ConfigVariableSearchPath(PyObject *args, ConfigVariableSearchPath *&coerced, bool &manage);
#endif
// GraphicsWindow
#ifndef LINK_ALL_STATIC
static struct Dtool_PyTypedObject *Dtool_Ptr_GraphicsWindow;
#else
extern struct Dtool_PyTypedObject Dtool_GraphicsWindow;
static struct Dtool_PyTypedObject *const Dtool_Ptr_GraphicsWindow = &Dtool_GraphicsWindow;
#endif

/**
 * Python wrappers for global functions
 */
/**
 * Python function wrapper for:
 * ConfigVariableSearchPath &get_particle_path(void)
 */
static PyObject *Dtool_get_particle_path_1(PyObject *, PyObject *) {
  // 1-ConfigVariableSearchPath &get_particle_path(void)
  ConfigVariableSearchPath *return_value = &(get_particle_path());
  if (Dtool_CheckErrorOccurred()) {
    return NULL;
  }
  return DTool_CreatePyInstance((void *)return_value, *Dtool_Ptr_ConfigVariableSearchPath, false, false);
}

#ifndef NDEBUG
static const char *Dtool_get_particle_path_1_comment =
  "C++ Interface:\n"
  "get_particle_path()\n";
#else
static const char *Dtool_get_particle_path_1_comment = NULL;
#endif

/**
 * Python function wrapper for:
 * void throw_new_frame(void)
 */
static PyObject *Dtool_throw_new_frame_2(PyObject *, PyObject *) {
  // 1-void throw_new_frame(void)
  throw_new_frame();
  return Dtool_Return_None();
}

#ifndef NDEBUG
static const char *Dtool_throw_new_frame_2_comment =
  "C++ Interface:\n"
  "throw_new_frame()\n";
#else
static const char *Dtool_throw_new_frame_2_comment = NULL;
#endif

/**
 * Python function wrapper for:
 * DConfig &get_config_showbase(void)
 */
static PyObject *Dtool_get_config_showbase_3(PyObject *, PyObject *) {
  // 1-DConfig &get_config_showbase(void)
  DConfig *return_value = &(get_config_showbase());
  if (Dtool_CheckErrorOccurred()) {
    return NULL;
  }
  return DTool_CreatePyInstance((void *)return_value, *Dtool_Ptr_DConfig, false, false);
}

#ifndef NDEBUG
static const char *Dtool_get_config_showbase_3_comment =
  "C++ Interface:\n"
  "get_config_showbase()\n"
  "\n"
  "// Returns the configure object for accessing config variables from a\n"
  "// scripting language.";
#else
static const char *Dtool_get_config_showbase_3_comment = NULL;
#endif

/**
 * Python function wrapper for:
 * void init_app_for_gui(void)
 */
static PyObject *Dtool_init_app_for_gui_4(PyObject *, PyObject *) {
  // 1-void init_app_for_gui(void)
  init_app_for_gui();
  return Dtool_Return_None();
}

#ifndef NDEBUG
static const char *Dtool_init_app_for_gui_4_comment =
  "C++ Interface:\n"
  "init_app_for_gui()\n";
#else
static const char *Dtool_init_app_for_gui_4_comment = NULL;
#endif

/**
 * Python function wrapper for:
 * void add_fullscreen_testsize(int xsize, int ysize)
 */
static PyObject *Dtool_add_fullscreen_testsize_5(PyObject *, PyObject *args, PyObject *kwds) {
  // 1-void add_fullscreen_testsize(int xsize, int ysize)
  int param0;
  int param1;
  static const char *keyword_list[] = {"xsize", "ysize", NULL};
  if (PyArg_ParseTupleAndKeywords(args, kwds, "ii:add_fullscreen_testsize", (char **)keyword_list, &param0, &param1)) {
    add_fullscreen_testsize((int)param0, (int)param1);
    return Dtool_Return_None();
  }
  if (!_PyErr_OCCURRED()) {
    return Dtool_Raise_BadArgumentsError(
      "add_fullscreen_testsize(int xsize, int ysize)\n");
  }
  return NULL;
}

#ifndef NDEBUG
static const char *Dtool_add_fullscreen_testsize_5_comment =
  "C++ Interface:\n"
  "add_fullscreen_testsize(int xsize, int ysize)\n"
  "\n"
  "// klunky interface since we cant pass array from python->C++";
#else
static const char *Dtool_add_fullscreen_testsize_5_comment = NULL;
#endif

/**
 * Python function wrapper for:
 * void runtest_fullscreen_sizes(GraphicsWindow *win)
 */
static PyObject *Dtool_runtest_fullscreen_sizes_6(PyObject *, PyObject *arg) {
  // 1-void runtest_fullscreen_sizes(GraphicsWindow *win)
  GraphicsWindow *arg_this = (GraphicsWindow *)DTOOL_Call_GetPointerThisClass(arg, Dtool_Ptr_GraphicsWindow, 0, "runtest_fullscreen_sizes", false, true);
  if (arg_this != NULL) {
    runtest_fullscreen_sizes(arg_this);
    return Dtool_Return_None();
  }
  if (!_PyErr_OCCURRED()) {
    return Dtool_Raise_BadArgumentsError(
      "runtest_fullscreen_sizes(GraphicsWindow win)\n");
  }
  return NULL;
}

#ifndef NDEBUG
static const char *Dtool_runtest_fullscreen_sizes_6_comment =
  "C++ Interface:\n"
  "runtest_fullscreen_sizes(GraphicsWindow win)\n";
#else
static const char *Dtool_runtest_fullscreen_sizes_6_comment = NULL;
#endif

/**
 * Python function wrapper for:
 * bool query_fullscreen_testresult(int xsize, int ysize)
 */
static PyObject *Dtool_query_fullscreen_testresult_7(PyObject *, PyObject *args, PyObject *kwds) {
  // 1-bool query_fullscreen_testresult(int xsize, int ysize)
  int param0;
  int param1;
  static const char *keyword_list[] = {"xsize", "ysize", NULL};
  if (PyArg_ParseTupleAndKeywords(args, kwds, "ii:query_fullscreen_testresult", (char **)keyword_list, &param0, &param1)) {
    bool return_value = query_fullscreen_testresult((int)param0, (int)param1);
    return Dtool_Return_Bool(return_value);
  }
  if (!_PyErr_OCCURRED()) {
    return Dtool_Raise_BadArgumentsError(
      "query_fullscreen_testresult(int xsize, int ysize)\n");
  }
  return NULL;
}

#ifndef NDEBUG
static const char *Dtool_query_fullscreen_testresult_7_comment =
  "C++ Interface:\n"
  "query_fullscreen_testresult(int xsize, int ysize)\n";
#else
static const char *Dtool_query_fullscreen_testresult_7_comment = NULL;
#endif

/**
 * Python function wrapper for:
 * void store_accessibility_shortcut_keys(void)
 */
static PyObject *Dtool_store_accessibility_shortcut_keys_8(PyObject *, PyObject *) {
  // 1-void store_accessibility_shortcut_keys(void)
  store_accessibility_shortcut_keys();
  return Dtool_Return_None();
}

#ifndef NDEBUG
static const char *Dtool_store_accessibility_shortcut_keys_8_comment =
  "C++ Interface:\n"
  "store_accessibility_shortcut_keys()\n"
  "\n"
  "// to handle windows stickykeys";
#else
static const char *Dtool_store_accessibility_shortcut_keys_8_comment = NULL;
#endif

/**
 * Python function wrapper for:
 * void allow_accessibility_shortcut_keys(bool allowKeys)
 */
static PyObject *Dtool_allow_accessibility_shortcut_keys_9(PyObject *, PyObject *arg) {
  // 1-void allow_accessibility_shortcut_keys(bool allowKeys)
  allow_accessibility_shortcut_keys((PyObject_IsTrue(arg) != 0));
  return Dtool_Return_None();
  if (!_PyErr_OCCURRED()) {
    return Dtool_Raise_BadArgumentsError(
      "allow_accessibility_shortcut_keys(bool allowKeys)\n");
  }
  return NULL;
}

#ifndef NDEBUG
static const char *Dtool_allow_accessibility_shortcut_keys_9_comment =
  "C++ Interface:\n"
  "allow_accessibility_shortcut_keys(bool allowKeys)\n";
#else
static const char *Dtool_allow_accessibility_shortcut_keys_9_comment = NULL;
#endif


/**
 * Module Object Linker ..
 */
void Dtool_libp3showbase_RegisterTypes() {
}

void Dtool_libp3showbase_ResolveExternals() {
#ifndef LINK_ALL_STATIC
  // Resolve externally imported types.
  Dtool_Ptr_DConfig = LookupNamedClass("DConfig");
  Dtool_Ptr_ConfigVariableSearchPath = LookupNamedClass("ConfigVariableSearchPath");
  Dtool_Ptr_GraphicsWindow = LookupRuntimeTypedClass(GraphicsWindow::get_class_type());
#endif
}

void Dtool_libp3showbase_BuildInstants(PyObject *module) {
  (void) module;
}

static PyMethodDef python_simple_funcs[] = {
  {"get_particle_path", &Dtool_get_particle_path_1, METH_NOARGS, (const char *)Dtool_get_particle_path_1_comment},
  {"getParticlePath", &Dtool_get_particle_path_1, METH_NOARGS, (const char *)Dtool_get_particle_path_1_comment},
  {"throw_new_frame", &Dtool_throw_new_frame_2, METH_NOARGS, (const char *)Dtool_throw_new_frame_2_comment},
  {"throwNewFrame", &Dtool_throw_new_frame_2, METH_NOARGS, (const char *)Dtool_throw_new_frame_2_comment},
  {"get_config_showbase", &Dtool_get_config_showbase_3, METH_NOARGS, (const char *)Dtool_get_config_showbase_3_comment},
  {"getConfigShowbase", &Dtool_get_config_showbase_3, METH_NOARGS, (const char *)Dtool_get_config_showbase_3_comment},
  {"init_app_for_gui", &Dtool_init_app_for_gui_4, METH_NOARGS, (const char *)Dtool_init_app_for_gui_4_comment},
  {"initAppForGui", &Dtool_init_app_for_gui_4, METH_NOARGS, (const char *)Dtool_init_app_for_gui_4_comment},
  {"add_fullscreen_testsize", (PyCFunction) &Dtool_add_fullscreen_testsize_5, METH_VARARGS | METH_KEYWORDS, (const char *)Dtool_add_fullscreen_testsize_5_comment},
  {"addFullscreenTestsize", (PyCFunction) &Dtool_add_fullscreen_testsize_5, METH_VARARGS | METH_KEYWORDS, (const char *)Dtool_add_fullscreen_testsize_5_comment},
  {"runtest_fullscreen_sizes", &Dtool_runtest_fullscreen_sizes_6, METH_O, (const char *)Dtool_runtest_fullscreen_sizes_6_comment},
  {"runtestFullscreenSizes", &Dtool_runtest_fullscreen_sizes_6, METH_O, (const char *)Dtool_runtest_fullscreen_sizes_6_comment},
  {"query_fullscreen_testresult", (PyCFunction) &Dtool_query_fullscreen_testresult_7, METH_VARARGS | METH_KEYWORDS, (const char *)Dtool_query_fullscreen_testresult_7_comment},
  {"queryFullscreenTestresult", (PyCFunction) &Dtool_query_fullscreen_testresult_7, METH_VARARGS | METH_KEYWORDS, (const char *)Dtool_query_fullscreen_testresult_7_comment},
  {"store_accessibility_shortcut_keys", &Dtool_store_accessibility_shortcut_keys_8, METH_NOARGS, (const char *)Dtool_store_accessibility_shortcut_keys_8_comment},
  {"storeAccessibilityShortcutKeys", &Dtool_store_accessibility_shortcut_keys_8, METH_NOARGS, (const char *)Dtool_store_accessibility_shortcut_keys_8_comment},
  {"allow_accessibility_shortcut_keys", &Dtool_allow_accessibility_shortcut_keys_9, METH_O, (const char *)Dtool_allow_accessibility_shortcut_keys_9_comment},
  {"allowAccessibilityShortcutKeys", &Dtool_allow_accessibility_shortcut_keys_9, METH_O, (const char *)Dtool_allow_accessibility_shortcut_keys_9_comment},
  // Support Function For Dtool_types ... for now in each module ??
  {"Dtool_BorrowThisReference", &Dtool_BorrowThisReference, METH_VARARGS, "Used to borrow 'this' pointer (to, from)\nAssumes no ownership."},
  {"Dtool_AddToDictionary", &Dtool_AddToDictionary, METH_VARARGS, "Used to add items into a tp_dict"},
  {NULL, NULL, 0, NULL}
};

struct LibraryDef libp3showbase_moddef = {python_simple_funcs};
static InterrogateModuleDef _in_module_def = {
  1478214733,  /* file_identifier */
  "libp3showbase",  /* library_name */
  "il41",  /* library_hash_name */
  "panda3d.direct",  /* module_name */
  "libp3showbase.in",  /* database_filename */
  (InterrogateUniqueNameDef *)0,  /* unique_names */
  0,  /* num_unique_names */
  (void **)0,  /* fptrs */
  0,  /* num_fptrs */
  1,  /* first_index */
  28  /* next_index */
};

Configure(_in_configure_libp3showbase);
ConfigureFn(_in_configure_libp3showbase) {
  interrogate_request_module(&_in_module_def);
}

