/*
 * This file was generated by:
 * built\bin\interrogate -v -srcdir panda/src/cull -Ipanda/src/cull -DCPPPARSER -D__STDC__=1 -D__cplusplus=201103L -DWIN32_VC -DWIN32 -D_WIN32 -D_M_IX86 -D_MSC_VER=1600 -D__declspec(param)= -D__cdecl -D_near -D_far -D__near -D__far -D__stdcall -oc built/tmp/libp3cull_igate.cxx -od built/pandac/input/libp3cull.in -fnames -string -refcount -assert -python-native -Sbuilt/include/parser-inc -Ipanda/src/cull -Sbuilt/tmp -Sbuilt/include -Sthirdparty/win-python/include -Sthirdparty/win-libs-vc10/extras/include -module panda3d.core -library libp3cull binCullHandler.h config_cull.h cullBinBackToFront.h cullBinFixed.h cullBinFrontToBack.h cullBinStateSorted.h cullBinUnsorted.h drawCullHandler.h p3cull_composite1.cxx p3cull_composite2.cxx 
 *
 */

#include "dtoolbase.h"
#include "interrogate_request.h"
#include "dconfig.h"
#include "pnotify.h"
#include <sstream>
#define PANDA_LIBRARY_NAME_libp3cull
#include "py_panda.h"
#include "extension.h"
#include "dcast.h"

#include "binCullHandler.h"
#include "configVariableBool.h"
#include "configVariableDouble.h"
#include "configVariableInt.h"
#include "config_cull.h"
#include "cullBin.h"
#include "cullBinBackToFront.h"
#include "cullBinFixed.h"
#include "cullBinFrontToBack.h"
#include "cullBinStateSorted.h"
#include "cullBinUnsorted.h"
#include "cullHandler.h"
#include "cullResult.h"
#include "cullableObject.h"
#include "dconfig.h"
#include "drawCullHandler.h"
#include "geom.h"
#include "notifyCategoryProxy.h"
#include "pandabase.h"
#include "pointerTo.h"
#include "renderState.h"
#include "transformState.h"

#undef _POSIX_C_SOURCE
#undef _XOPEN_SOURCE
#define PY_SSIZE_T_CLEAN 1

#if PYTHON_FRAMEWORK
  #include <Python/Python.h>
#else
  #include "Python.h"
#endif

/**
 * Extern declarations for imported classes
 */

/**
 * Python wrappers for global functions
 */

/**
 * Module Object Linker ..
 */
void Dtool_libp3cull_RegisterTypes() {
}

void Dtool_libp3cull_ResolveExternals() {
#ifndef LINK_ALL_STATIC
  // Resolve externally imported types.
#endif
}

void Dtool_libp3cull_BuildInstants(PyObject *module) {
  (void) module;
}

static PyMethodDef python_simple_funcs[] = {
  // Support Function For Dtool_types ... for now in each module ??
  {"Dtool_BorrowThisReference", &Dtool_BorrowThisReference, METH_VARARGS, "Used to borrow 'this' pointer (to, from)\nAssumes no ownership."},
  {"Dtool_AddToDictionary", &Dtool_AddToDictionary, METH_VARARGS, "Used to add items into a tp_dict"},
  {NULL, NULL, 0, NULL}
};

struct LibraryDef libp3cull_moddef = {python_simple_funcs};
static InterrogateModuleDef _in_module_def = {
  1478212582,  /* file_identifier */
  "libp3cull",  /* library_name */
  "dIX7",  /* library_hash_name */
  "panda3d.core",  /* module_name */
  "libp3cull.in",  /* database_filename */
  (InterrogateUniqueNameDef *)0,  /* unique_names */
  0,  /* num_unique_names */
  (void **)0,  /* fptrs */
  0,  /* num_fptrs */
  1,  /* first_index */
  1  /* next_index */
};

Configure(_in_configure_libp3cull);
ConfigureFn(_in_configure_libp3cull) {
  interrogate_request_module(&_in_module_def);
}

