/*
 * This file was generated by:
 * built\bin\interrogate -v -srcdir direct/src/motiontrail -Idirect/src/motiontrail -DCPPPARSER -D__STDC__=1 -D__cplusplus=201103L -DWIN32_VC -DWIN32 -D_WIN32 -D_M_IX86 -D_MSC_VER=1600 -D__declspec(param)= -D__cdecl -D_near -D_far -D__near -D__far -D__stdcall -oc built/tmp/libp3motiontrail_igate.cxx -od built/pandac/input/libp3motiontrail.in -fnames -string -refcount -assert -python-native -Sbuilt/include/parser-inc -Idirect/src/motiontrail -Sbuilt/tmp -Sbuilt/include -Sthirdparty/win-python/include -Sthirdparty/win-libs-vc10/extras/include -module panda3d.direct -library libp3motiontrail cMotionTrail.cxx cMotionTrail.h config_motiontrail.h 
 *
 */

#include "dtoolbase.h"
#include "interrogate_request.h"
#include "dconfig.h"
#include "pnotify.h"
#include <sstream>
#define PANDA_LIBRARY_NAME_libp3motiontrail
#include "py_panda.h"
#include "extension.h"
#include "dcast.h"

#include "cMotionTrail.h"
#include "colorAttrib.h"
#include "config_motiontrail.h"
#include "dconfig.h"
#include "directbase.h"
#include "notifyCategoryProxy.h"
#include "renderState.h"

#undef _POSIX_C_SOURCE
#undef _XOPEN_SOURCE
#define PY_SSIZE_T_CLEAN 1

#if PYTHON_FRAMEWORK
  #include <Python/Python.h>
#else
  #include "Python.h"
#endif

/**
 * Forward declarations for top-level class CMotionTrail
 */
typedef CMotionTrail CMotionTrail_localtype;
Define_Module_ClassRef(panda3d.direct, CMotionTrail, CMotionTrail_localtype, CMotionTrail);
static struct Dtool_PyTypedObject *const Dtool_Ptr_CMotionTrail = &Dtool_CMotionTrail;
static void Dtool_PyModuleClassInit_CMotionTrail(PyObject *module);

/**
 * Extern declarations for imported classes
 */
// ReferenceCount
#ifndef LINK_ALL_STATIC
static struct Dtool_PyTypedObject *Dtool_Ptr_ReferenceCount;
#else
extern struct Dtool_PyTypedObject Dtool_ReferenceCount;
static struct Dtool_PyTypedObject *const Dtool_Ptr_ReferenceCount = &Dtool_ReferenceCount;
#endif
// TypeHandle
#ifndef LINK_ALL_STATIC
static struct Dtool_PyTypedObject *Dtool_Ptr_TypeHandle;
inline static TypeHandle *Dtool_Coerce_TypeHandle(PyObject *args, TypeHandle &coerced) {
  nassertr(Dtool_Ptr_TypeHandle != NULL, NULL);
  nassertr(Dtool_Ptr_TypeHandle->_Dtool_Coerce != NULL, NULL);
  return ((TypeHandle *(*)(PyObject *, TypeHandle &))Dtool_Ptr_TypeHandle->_Dtool_Coerce)(args, coerced);
}
#else
extern struct Dtool_PyTypedObject Dtool_TypeHandle;
static struct Dtool_PyTypedObject *const Dtool_Ptr_TypeHandle = &Dtool_TypeHandle;
extern TypeHandle *Dtool_Coerce_TypeHandle(PyObject *args, TypeHandle &coerced);
#endif
// TypedObject
#ifndef LINK_ALL_STATIC
static struct Dtool_PyTypedObject *Dtool_Ptr_TypedObject;
#else
extern struct Dtool_PyTypedObject Dtool_TypedObject;
static struct Dtool_PyTypedObject *const Dtool_Ptr_TypedObject = &Dtool_TypedObject;
#endif
// TypedReferenceCount
#ifndef LINK_ALL_STATIC
static struct Dtool_PyTypedObject *Dtool_Ptr_TypedReferenceCount;
#else
extern struct Dtool_PyTypedObject Dtool_TypedReferenceCount;
static struct Dtool_PyTypedObject *const Dtool_Ptr_TypedReferenceCount = &Dtool_TypedReferenceCount;
#endif
// LVector4f
#ifndef LINK_ALL_STATIC
static struct Dtool_PyTypedObject *Dtool_Ptr_LVector4f;
inline static LVector4f *Dtool_Coerce_LVector4f(PyObject *args, LVector4f &coerced) {
  nassertr(Dtool_Ptr_LVector4f != NULL, NULL);
  nassertr(Dtool_Ptr_LVector4f->_Dtool_Coerce != NULL, NULL);
  return ((LVector4f *(*)(PyObject *, LVector4f &))Dtool_Ptr_LVector4f->_Dtool_Coerce)(args, coerced);
}
#else
extern struct Dtool_PyTypedObject Dtool_LVector4f;
static struct Dtool_PyTypedObject *const Dtool_Ptr_LVector4f = &Dtool_LVector4f;
extern LVector4f *Dtool_Coerce_LVector4f(PyObject *args, LVector4f &coerced);
#endif
// LMatrix4f
#ifndef LINK_ALL_STATIC
static struct Dtool_PyTypedObject *Dtool_Ptr_LMatrix4f;
inline static LMatrix4f *Dtool_Coerce_LMatrix4f(PyObject *args, LMatrix4f &coerced) {
  nassertr(Dtool_Ptr_LMatrix4f != NULL, NULL);
  nassertr(Dtool_Ptr_LMatrix4f->_Dtool_Coerce != NULL, NULL);
  return ((LMatrix4f *(*)(PyObject *, LMatrix4f &))Dtool_Ptr_LMatrix4f->_Dtool_Coerce)(args, coerced);
}
#else
extern struct Dtool_PyTypedObject Dtool_LMatrix4f;
static struct Dtool_PyTypedObject *const Dtool_Ptr_LMatrix4f = &Dtool_LMatrix4f;
extern LMatrix4f *Dtool_Coerce_LMatrix4f(PyObject *args, LMatrix4f &coerced);
#endif
// GeomNode
#ifndef LINK_ALL_STATIC
static struct Dtool_PyTypedObject *Dtool_Ptr_GeomNode;
#else
extern struct Dtool_PyTypedObject Dtool_GeomNode;
static struct Dtool_PyTypedObject *const Dtool_Ptr_GeomNode = &Dtool_GeomNode;
#endif

/**
 * Python wrappers for global functions
 */
/**
 * Python wrappers for functions of class CMotionTrail
 */
/**
 * Python function wrapper for:
 * void CMotionTrail::reset(void)
 */
static PyObject *Dtool_CMotionTrail_reset_4(PyObject *self, PyObject *) {
  CMotionTrail *local_this = NULL;
  if (!Dtool_Call_ExtractThisPointer_NonConst(self, Dtool_CMotionTrail, (void **)&local_this, "CMotionTrail.reset")) {
    return NULL;
  }
  // 1-void CMotionTrail::reset(void)
  (*local_this).reset();
  return Dtool_Return_None();
}

#ifndef NDEBUG
static const char *Dtool_CMotionTrail_reset_4_comment =
  "C++ Interface:\n"
  "reset(const CMotionTrail self)\n"
  "\n"
  "/**\n"
  " * Reset the frame sample history.\n"
  " */";
#else
static const char *Dtool_CMotionTrail_reset_4_comment = NULL;
#endif

/**
 * Python function wrapper for:
 * void CMotionTrail::reset_vertex_list(void)
 */
static PyObject *Dtool_CMotionTrail_reset_vertex_list_5(PyObject *self, PyObject *) {
  CMotionTrail *local_this = NULL;
  if (!Dtool_Call_ExtractThisPointer_NonConst(self, Dtool_CMotionTrail, (void **)&local_this, "CMotionTrail.reset_vertex_list")) {
    return NULL;
  }
  // 1-void CMotionTrail::reset_vertex_list(void)
  (*local_this).reset_vertex_list();
  return Dtool_Return_None();
}

#ifndef NDEBUG
static const char *Dtool_CMotionTrail_reset_vertex_list_5_comment =
  "C++ Interface:\n"
  "reset_vertex_list(const CMotionTrail self)\n"
  "\n"
  "/**\n"
  " * Reset the vertex list.\n"
  " */";
#else
static const char *Dtool_CMotionTrail_reset_vertex_list_5_comment = NULL;
#endif

/**
 * Python function wrapper for:
 * void CMotionTrail::enable(bool enable)
 */
static PyObject *Dtool_CMotionTrail_enable_6(PyObject *self, PyObject *arg) {
  CMotionTrail *local_this = NULL;
  if (!Dtool_Call_ExtractThisPointer_NonConst(self, Dtool_CMotionTrail, (void **)&local_this, "CMotionTrail.enable")) {
    return NULL;
  }
  // 1-void CMotionTrail::enable(bool enable)
  (*local_this).enable((PyObject_IsTrue(arg) != 0));
  return Dtool_Return_None();
  if (!_PyErr_OCCURRED()) {
    return Dtool_Raise_BadArgumentsError(
      "enable(const CMotionTrail self, bool enable)\n");
  }
  return NULL;
}

#ifndef NDEBUG
static const char *Dtool_CMotionTrail_enable_6_comment =
  "C++ Interface:\n"
  "enable(const CMotionTrail self, bool enable)\n"
  "\n"
  "/**\n"
  " * Enable/disable the motion trail.\n"
  " */";
#else
static const char *Dtool_CMotionTrail_enable_6_comment = NULL;
#endif

/**
 * Python function wrapper for:
 * void CMotionTrail::set_geom_node(GeomNode *geom_node)
 */
static PyObject *Dtool_CMotionTrail_set_geom_node_7(PyObject *self, PyObject *arg) {
  CMotionTrail *local_this = NULL;
  if (!Dtool_Call_ExtractThisPointer_NonConst(self, Dtool_CMotionTrail, (void **)&local_this, "CMotionTrail.set_geom_node")) {
    return NULL;
  }
  // 1-void CMotionTrail::set_geom_node(GeomNode *geom_node)
  GeomNode *arg_this = (GeomNode *)DTOOL_Call_GetPointerThisClass(arg, Dtool_Ptr_GeomNode, 1, "CMotionTrail.set_geom_node", false, true);
  if (arg_this != NULL) {
    (*local_this).set_geom_node(arg_this);
    return Dtool_Return_None();
  }
  if (!_PyErr_OCCURRED()) {
    return Dtool_Raise_BadArgumentsError(
      "set_geom_node(const CMotionTrail self, GeomNode geom_node)\n");
  }
  return NULL;
}

#ifndef NDEBUG
static const char *Dtool_CMotionTrail_set_geom_node_7_comment =
  "C++ Interface:\n"
  "set_geom_node(const CMotionTrail self, GeomNode geom_node)\n"
  "\n"
  "/**\n"
  " * Set the GeomNode.\n"
  " */";
#else
static const char *Dtool_CMotionTrail_set_geom_node_7_comment = NULL;
#endif

/**
 * Python function wrapper for:
 * void CMotionTrail::add_vertex(LVector4 *vertex, LVector4 *start_color, LVector4 *end_color, PN_stdfloat v)
 */
static PyObject *Dtool_CMotionTrail_add_vertex_8(PyObject *self, PyObject *args, PyObject *kwds) {
  CMotionTrail *local_this = NULL;
  if (!Dtool_Call_ExtractThisPointer_NonConst(self, Dtool_CMotionTrail, (void **)&local_this, "CMotionTrail.add_vertex")) {
    return NULL;
  }
  // 1-void CMotionTrail::add_vertex(LVector4 *vertex, LVector4 *start_color, LVector4 *end_color, PN_stdfloat v)
  PyObject *param1;
  PyObject *param2;
  PyObject *param3;
  float param4;
  static const char *keyword_list[] = {"vertex", "start_color", "end_color", "v", NULL};
  if (PyArg_ParseTupleAndKeywords(args, kwds, "OOOf:add_vertex", (char **)keyword_list, &param1, &param2, &param3, &param4)) {
    LVector4f param1_local;
    LVector4 *param1_this = Dtool_Coerce_LVector4f(param1, param1_local);
    if (!(param1_this != NULL)) {
      return Dtool_Raise_ArgTypeError(param1, 1, "CMotionTrail.add_vertex", "LVector4f");
    }
    LVector4f param2_local;
    LVector4 *param2_this = Dtool_Coerce_LVector4f(param2, param2_local);
    if (!(param2_this != NULL)) {
      return Dtool_Raise_ArgTypeError(param2, 2, "CMotionTrail.add_vertex", "LVector4f");
    }
    LVector4f param3_local;
    LVector4 *param3_this = Dtool_Coerce_LVector4f(param3, param3_local);
    if (!(param3_this != NULL)) {
      return Dtool_Raise_ArgTypeError(param3, 3, "CMotionTrail.add_vertex", "LVector4f");
    }
    (*local_this).add_vertex(param1_this, param2_this, param3_this, (PN_stdfloat)param4);
    return Dtool_Return_None();
  }
  if (!_PyErr_OCCURRED()) {
    return Dtool_Raise_BadArgumentsError(
      "add_vertex(const CMotionTrail self, LVector4f vertex, LVector4f start_color, LVector4f end_color, float v)\n");
  }
  return NULL;
}

#ifndef NDEBUG
static const char *Dtool_CMotionTrail_add_vertex_8_comment =
  "C++ Interface:\n"
  "add_vertex(const CMotionTrail self, LVector4f vertex, LVector4f start_color, LVector4f end_color, float v)\n"
  "\n"
  "/**\n"
  " * Add a vertex.\n"
  " */";
#else
static const char *Dtool_CMotionTrail_add_vertex_8_comment = NULL;
#endif

/**
 * Python function wrapper for:
 * void CMotionTrail::set_parameters(PN_stdfloat sampling_time, PN_stdfloat time_window, bool use_texture, bool calculate_relative_matrix, bool use_nurbs, PN_stdfloat resolution_distance)
 */
static PyObject *Dtool_CMotionTrail_set_parameters_9(PyObject *self, PyObject *args, PyObject *kwds) {
  CMotionTrail *local_this = NULL;
  if (!Dtool_Call_ExtractThisPointer_NonConst(self, Dtool_CMotionTrail, (void **)&local_this, "CMotionTrail.set_parameters")) {
    return NULL;
  }
  // 1-void CMotionTrail::set_parameters(PN_stdfloat sampling_time, PN_stdfloat time_window, bool use_texture, bool calculate_relative_matrix, bool use_nurbs, PN_stdfloat resolution_distance)
  float param1;
  float param2;
  PyObject *param3;
  PyObject *param4;
  PyObject *param5;
  float param6;
  static const char *keyword_list[] = {"sampling_time", "time_window", "use_texture", "calculate_relative_matrix", "use_nurbs", "resolution_distance", NULL};
  if (PyArg_ParseTupleAndKeywords(args, kwds, "ffOOOf:set_parameters", (char **)keyword_list, &param1, &param2, &param3, &param4, &param5, &param6)) {
    (*local_this).set_parameters((PN_stdfloat)param1, (PN_stdfloat)param2, (PyObject_IsTrue(param3) != 0), (PyObject_IsTrue(param4) != 0), (PyObject_IsTrue(param5) != 0), (PN_stdfloat)param6);
    return Dtool_Return_None();
  }
  if (!_PyErr_OCCURRED()) {
    return Dtool_Raise_BadArgumentsError(
      "set_parameters(const CMotionTrail self, float sampling_time, float time_window, bool use_texture, bool calculate_relative_matrix, bool use_nurbs, float resolution_distance)\n");
  }
  return NULL;
}

#ifndef NDEBUG
static const char *Dtool_CMotionTrail_set_parameters_9_comment =
  "C++ Interface:\n"
  "set_parameters(const CMotionTrail self, float sampling_time, float time_window, bool use_texture, bool calculate_relative_matrix, bool use_nurbs, float resolution_distance)\n"
  "\n"
  "/**\n"
  " * Set motion trail parameters.\n"
  " *\n"
  " * sampling_time = Can be used to specify a lower sampling rate than the frame\n"
  " * rate.  Use 0.0 with nurbs.\n"
  " *\n"
  " * time_window = a component for the \"length\" of the motion trail.  The motion\n"
  " * trail length = time_window * velocity of the object.\n"
  " *\n"
  " * use_texture = texture option on/off.\n"
  " *\n"
  " * calculate_relative_matrix = calculate relative matrix on/off.\n"
  " *\n"
  " * use_nurbs = nurbs option on/off\n"
  " *\n"
  " * resolution_distance = the distance used to determine the number of geometry\n"
  " * samples.  samples = motion trail length / resolution_distance.  Applicable\n"
  " * only if nurbs is on.\n"
  " */";
#else
static const char *Dtool_CMotionTrail_set_parameters_9_comment = NULL;
#endif

/**
 * Python function wrapper for:
 * int CMotionTrail::check_for_update(PN_stdfloat current_time)
 */
static PyObject *Dtool_CMotionTrail_check_for_update_10(PyObject *self, PyObject *arg) {
  CMotionTrail *local_this = NULL;
  if (!Dtool_Call_ExtractThisPointer_NonConst(self, Dtool_CMotionTrail, (void **)&local_this, "CMotionTrail.check_for_update")) {
    return NULL;
  }
  // 1-int CMotionTrail::check_for_update(PN_stdfloat current_time)
  if (PyNumber_Check(arg)) {
    int return_value = (*local_this).check_for_update((PN_stdfloat)PyFloat_AsDouble(arg));
    if (Dtool_CheckErrorOccurred()) {
      return NULL;
    }
    return Dtool_WrapValue(return_value);
  }
  if (!_PyErr_OCCURRED()) {
    return Dtool_Raise_BadArgumentsError(
      "check_for_update(const CMotionTrail self, float current_time)\n");
  }
  return NULL;
}

#ifndef NDEBUG
static const char *Dtool_CMotionTrail_check_for_update_10_comment =
  "C++ Interface:\n"
  "check_for_update(const CMotionTrail self, float current_time)\n"
  "\n"
  "/**\n"
  " * Check if a sample can be submitted.\n"
  " */";
#else
static const char *Dtool_CMotionTrail_check_for_update_10_comment = NULL;
#endif

/**
 * Python function wrapper for:
 * void CMotionTrail::update_motion_trail(PN_stdfloat current_time, LMatrix4 *transform)
 */
static PyObject *Dtool_CMotionTrail_update_motion_trail_11(PyObject *self, PyObject *args, PyObject *kwds) {
  CMotionTrail *local_this = NULL;
  if (!Dtool_Call_ExtractThisPointer_NonConst(self, Dtool_CMotionTrail, (void **)&local_this, "CMotionTrail.update_motion_trail")) {
    return NULL;
  }
  // 1-void CMotionTrail::update_motion_trail(PN_stdfloat current_time, LMatrix4 *transform)
  float param1;
  PyObject *param2;
  static const char *keyword_list[] = {"current_time", "transform", NULL};
  if (PyArg_ParseTupleAndKeywords(args, kwds, "fO:update_motion_trail", (char **)keyword_list, &param1, &param2)) {
    LMatrix4f param2_local;
    LMatrix4 *param2_this = Dtool_Coerce_LMatrix4f(param2, param2_local);
    if (!(param2_this != NULL)) {
      return Dtool_Raise_ArgTypeError(param2, 2, "CMotionTrail.update_motion_trail", "LMatrix4f");
    }
    (*local_this).update_motion_trail((PN_stdfloat)param1, param2_this);
    return Dtool_Return_None();
  }
  if (!_PyErr_OCCURRED()) {
    return Dtool_Raise_BadArgumentsError(
      "update_motion_trail(const CMotionTrail self, float current_time, LMatrix4f transform)\n");
  }
  return NULL;
}

#ifndef NDEBUG
static const char *Dtool_CMotionTrail_update_motion_trail_11_comment =
  "C++ Interface:\n"
  "update_motion_trail(const CMotionTrail self, float current_time, LMatrix4f transform)\n"
  "\n"
  "/**\n"
  " * See class header comments.\n"
  " */";
#else
static const char *Dtool_CMotionTrail_update_motion_trail_11_comment = NULL;
#endif

/**
 * Python function wrapper for:
 * static TypeHandle CMotionTrail::get_class_type(void)
 */
static PyObject *Dtool_CMotionTrail_get_class_type_12(PyObject *, PyObject *) {
  // 1-static TypeHandle CMotionTrail::get_class_type(void)
  TypeHandle *return_value = new TypeHandle(CMotionTrail::get_class_type());
  if (return_value == NULL) {
    return PyErr_NoMemory();
  }
  if (Dtool_CheckErrorOccurred()) {
    delete return_value;
    return NULL;
  }
  return DTool_CreatePyInstance((void *)return_value, *Dtool_Ptr_TypeHandle, true, false);
}

#ifndef NDEBUG
static const char *Dtool_CMotionTrail_get_class_type_12_comment =
  "C++ Interface:\n"
  "get_class_type()\n";
#else
static const char *Dtool_CMotionTrail_get_class_type_12_comment = NULL;
#endif

/**
 * Python function wrapper for:
 * CMotionTrail::CMotionTrail(void)
 * inline CMotionTrail::CMotionTrail(CMotionTrail const &) = default
 */
static int Dtool_Init_CMotionTrail(PyObject *self, PyObject *args, PyObject *kwds) {
  int parameter_count = (int)PyTuple_Size(args);
  if (kwds != NULL) {
    parameter_count += (int)PyDict_Size(kwds);
  }
  switch (parameter_count) {
  case 0:
    {
      // 1-CMotionTrail::CMotionTrail(void)
      CMotionTrail *return_value = new CMotionTrail();
      if (return_value == NULL) {
        PyErr_NoMemory();
        return -1;
      }
      return_value->ref();
      if (Dtool_CheckErrorOccurred()) {
        unref_delete(return_value);
        return -1;
      }
      return DTool_PyInit_Finalize(self, (void *)return_value, &Dtool_CMotionTrail, true, false);
    }
    break;
  case 1:
    {
      PyObject *arg = NULL;
      if (PyTuple_GET_SIZE(args) == 1) {
        arg = PyTuple_GET_ITEM(args, 0);
      } else if (kwds != NULL) {
        arg = PyDict_GetItemString(kwds, "param0");
      }
      if (arg == (PyObject *)NULL) {
        Dtool_Raise_TypeError("Required argument 'param0' (pos 1) not found");
        return -1;
      }
      // 1-inline CMotionTrail::CMotionTrail(CMotionTrail const &) = default
      CMotionTrail const *arg_this = (CMotionTrail *)DTOOL_Call_GetPointerThisClass(arg, Dtool_Ptr_CMotionTrail, 0, "CMotionTrail.CMotionTrail", true, true);
      if (arg_this != NULL) {
        CMotionTrail *return_value = new CMotionTrail(*arg_this);
        if (return_value == NULL) {
          PyErr_NoMemory();
          return -1;
        }
        return_value->ref();
        if (Dtool_CheckErrorOccurred()) {
          unref_delete(return_value);
          return -1;
        }
        return DTool_PyInit_Finalize(self, (void *)return_value, &Dtool_CMotionTrail, true, false);
      }
    }
    break;
#ifndef NDEBUG
  default:
    PyErr_Format(PyExc_TypeError,
                 "CMotionTrail() takes 0 or 1 arguments (%d given)",
                 parameter_count);
    return -1;
#endif
  }
  if (!_PyErr_OCCURRED()) {
    Dtool_Raise_BadArgumentsError(
      "CMotionTrail()\n"
      "CMotionTrail(const CMotionTrail param0)\n");
  }
  return -1;
}

static void *Dtool_UpcastInterface_CMotionTrail(PyObject *self, Dtool_PyTypedObject *requested_type) {
  Dtool_PyTypedObject *SelfType = ((Dtool_PyInstDef *)self)->_My_Type;
  if (SelfType != Dtool_Ptr_CMotionTrail) {
    printf("CMotionTrail ** Bad Source Type-- Requesting Conversion from %s to %s\n", Py_TYPE(self)->tp_name, requested_type->_PyType.tp_name); fflush(NULL);
    return NULL;
  }

  CMotionTrail *local_this = (CMotionTrail *)((Dtool_PyInstDef *)self)->_ptr_to_object;
  if (requested_type == Dtool_Ptr_CMotionTrail) {
    return local_this;
  }
  if (requested_type == Dtool_Ptr_ReferenceCount) {
    return (ReferenceCount *)(TypedReferenceCount *) local_this;
  }
  if (requested_type == Dtool_Ptr_TypedObject) {
    return (TypedObject *)(TypedReferenceCount *) local_this;
  }
  if (requested_type == Dtool_Ptr_TypedReferenceCount) {
    return (TypedReferenceCount *) local_this;
  }
  return NULL;
}

static void *Dtool_DowncastInterface_CMotionTrail(void *from_this, Dtool_PyTypedObject *from_type) {
  if (from_this == NULL || from_type == NULL) {
    return NULL;
  }
  if (from_type == Dtool_Ptr_CMotionTrail) {
    return from_this;
  }
  if (from_type == Dtool_Ptr_ReferenceCount) {
    ReferenceCount* other_this = (ReferenceCount*)from_this;
    return (CMotionTrail*)other_this;
  }
  if (from_type == Dtool_Ptr_TypedObject) {
    TypedObject* other_this = (TypedObject*)from_this;
    return (CMotionTrail*)other_this;
  }
  if (from_type == Dtool_Ptr_TypedReferenceCount) {
    TypedReferenceCount* other_this = (TypedReferenceCount*)from_this;
    return (CMotionTrail*)other_this;
  }
  return (void *) NULL;
}

/**
 * Python method tables for CMotionTrail (CMotionTrail)
 */
static PyMethodDef Dtool_Methods_CMotionTrail[] = {
  {"reset", &Dtool_CMotionTrail_reset_4, METH_NOARGS, (const char *)Dtool_CMotionTrail_reset_4_comment},
  {"reset_vertex_list", &Dtool_CMotionTrail_reset_vertex_list_5, METH_NOARGS, (const char *)Dtool_CMotionTrail_reset_vertex_list_5_comment},
  {"resetVertexList", &Dtool_CMotionTrail_reset_vertex_list_5, METH_NOARGS, (const char *)Dtool_CMotionTrail_reset_vertex_list_5_comment},
  {"enable", &Dtool_CMotionTrail_enable_6, METH_O, (const char *)Dtool_CMotionTrail_enable_6_comment},
  {"set_geom_node", &Dtool_CMotionTrail_set_geom_node_7, METH_O, (const char *)Dtool_CMotionTrail_set_geom_node_7_comment},
  {"setGeomNode", &Dtool_CMotionTrail_set_geom_node_7, METH_O, (const char *)Dtool_CMotionTrail_set_geom_node_7_comment},
  {"add_vertex", (PyCFunction) &Dtool_CMotionTrail_add_vertex_8, METH_VARARGS | METH_KEYWORDS, (const char *)Dtool_CMotionTrail_add_vertex_8_comment},
  {"addVertex", (PyCFunction) &Dtool_CMotionTrail_add_vertex_8, METH_VARARGS | METH_KEYWORDS, (const char *)Dtool_CMotionTrail_add_vertex_8_comment},
  {"set_parameters", (PyCFunction) &Dtool_CMotionTrail_set_parameters_9, METH_VARARGS | METH_KEYWORDS, (const char *)Dtool_CMotionTrail_set_parameters_9_comment},
  {"setParameters", (PyCFunction) &Dtool_CMotionTrail_set_parameters_9, METH_VARARGS | METH_KEYWORDS, (const char *)Dtool_CMotionTrail_set_parameters_9_comment},
  {"check_for_update", &Dtool_CMotionTrail_check_for_update_10, METH_O, (const char *)Dtool_CMotionTrail_check_for_update_10_comment},
  {"checkForUpdate", &Dtool_CMotionTrail_check_for_update_10, METH_O, (const char *)Dtool_CMotionTrail_check_for_update_10_comment},
  {"update_motion_trail", (PyCFunction) &Dtool_CMotionTrail_update_motion_trail_11, METH_VARARGS | METH_KEYWORDS, (const char *)Dtool_CMotionTrail_update_motion_trail_11_comment},
  {"updateMotionTrail", (PyCFunction) &Dtool_CMotionTrail_update_motion_trail_11, METH_VARARGS | METH_KEYWORDS, (const char *)Dtool_CMotionTrail_update_motion_trail_11_comment},
  {"get_class_type", &Dtool_CMotionTrail_get_class_type_12, METH_NOARGS | METH_STATIC, (const char *)Dtool_CMotionTrail_get_class_type_12_comment},
  {"getClassType", &Dtool_CMotionTrail_get_class_type_12, METH_NOARGS | METH_STATIC, (const char *)Dtool_CMotionTrail_get_class_type_12_comment},
  {"__copy__", &copy_from_copy_constructor, METH_NOARGS, NULL},
  {"__deepcopy__", &map_deepcopy_to_copy, METH_VARARGS, NULL},
  {NULL, NULL, 0, NULL}
};

static PyNumberMethods Dtool_NumberMethods_CMotionTrail = {
  0, // nb_add
  0, // nb_subtract
  0, // nb_multiply
#if PY_MAJOR_VERSION < 3
  0, // nb_divide
#endif
  0, // nb_remainder
  0, // nb_divmod
  0, // nb_power
  0, // nb_negative
  0, // nb_positive
  0, // nb_absolute
  0, // nb_bool
  0, // nb_invert
  0, // nb_lshift
  0, // nb_rshift
  0, // nb_and
  0, // nb_xor
  0, // nb_or
#if PY_MAJOR_VERSION < 3
  0, // nb_coerce
#endif
  0, // nb_int
  0, // nb_long
  0, // nb_float
#if PY_MAJOR_VERSION < 3
  0, // nb_oct
  0, // nb_hex
#endif
  0, // nb_inplace_add
  0, // nb_inplace_subtract
  0, // nb_inplace_multiply
#if PY_MAJOR_VERSION < 3
  0, // nb_inplace_divide
#endif
  0, // nb_inplace_remainder
  0, // nb_inplace_power
  0, // nb_inplace_lshift
  0, // nb_inplace_rshift
  0, // nb_inplace_and
  0, // nb_inplace_xor
  0, // nb_inplace_or
  0, // nb_floor_divide
  0, // nb_true_divide
  0, // nb_inplace_floor_divide
  0, // nb_inplace_true_divide
#if PY_VERSION_HEX >= 0x02050000
  0, // nb_index
#endif
#if PY_VERSION_HEX >= 0x03050000
  0, // nb_matrix_multiply
  0, // nb_inplace_matrix_multiply
#endif
};

static PySequenceMethods Dtool_SequenceMethods_CMotionTrail = {
  0, // sq_length
  0, // sq_concat
  0, // sq_repeat
  0, // sq_item
  0, // sq_slice
  0, // sq_ass_item
  0, // sq_ass_slice
  0, // sq_contains
  0, // sq_inplace_concat
  0, // sq_inplace_repeat
};

static PyMappingMethods Dtool_MappingMethods_CMotionTrail = {
  0, // mp_length
  0, // mp_subscript
  0, // mp_ass_subscript
};

static PyBufferProcs Dtool_BufferProcs_CMotionTrail = {
#if PY_MAJOR_VERSION < 3
  0, // bf_getreadbuffer
  0, // bf_getwritebuffer
  0, // bf_getsegcount
  0, // bf_getcharbuffer
#endif
#if PY_VERSION_HEX >= 0x02060000
  0, // bf_getbuffer
  0, // bf_releasebuffer
#endif
};

struct Dtool_PyTypedObject Dtool_CMotionTrail = {
  {
    PyVarObject_HEAD_INIT(NULL, 0)
    "panda3d.direct.CMotionTrail",
    sizeof(Dtool_PyInstDef),
    0, // tp_itemsize
    &Dtool_FreeInstance_CMotionTrail,
    0, // tp_print
    0, // tp_getattr
    0, // tp_setattr
#if PY_MAJOR_VERSION >= 3
    0, // tp_reserved
#else
    0, // tp_compare
#endif
    0, // tp_repr
    &Dtool_NumberMethods_CMotionTrail,
    &Dtool_SequenceMethods_CMotionTrail,
    &Dtool_MappingMethods_CMotionTrail,
    0, // tp_hash
    0, // tp_call
    0, // tp_str
    PyObject_GenericGetAttr,
    PyObject_GenericSetAttr,
    &Dtool_BufferProcs_CMotionTrail,
    Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE | Py_TPFLAGS_CHECKTYPES,
#ifdef NDEBUG
    0,
#else
    "/**\n"
    " * The method used in creating the motion trail is based on taking samples of\n"
    " * time and transformations (the position and orientation matrix) in real-\n"
    " * time.  The method also requires a number of vertices (positions) that\n"
    " * determines \"shape\" of the motion trail (i.e.  the edge of a blade).  A\n"
    " * start color and end color is also required for each vertex.  The color is\n"
    " * interpolated as function of time.  The colors are typically used to fade\n"
    " * the motion trail so the end color is typically black.\n"
    " *\n"
    " * The vertices are submitted via the \"add_vertex\" function.  For each frame,\n"
    " * a sample is submited via the \"update_motion_trail\" function.  During the\n"
    " * \"update_motion_trail\" function, the motion trail geometry is created\n"
    " * dynamically from the sample history and the vertices.\n"
    " *\n"
    " * The user must specifiy a GeomNode via \"set_geom_node\".\n"
    " *\n"
    " * The duration of the sample history is specified by a time window.  A larger\n"
    " * time window creates longer motion trails (given constant speed).  Samples\n"
    " * that are no longer within the time window are automatically discarded.\n"
    " *\n"
    " * The nurbs option can be used to create smooth interpolated curves from the\n"
    " * samples.  The nurbs option is useful for animations that lack sampling to\n"
    " * begin with, animations that move very quickly, or low frame rates.\n"
    " *\n"
    " * The texture option be used to create variation to the motion trail.  The u\n"
    " * coordinate of the texture corresponds to time and the v coordinate\n"
    " * corresponds to the \"shape\" of the motion trail.\n"
    " */",
#endif
    0, // tp_traverse
    0, // tp_clear
    0, // tp_richcompare
    0, // tp_weaklistoffset
    0, // tp_iter
    0, // tp_iternext
    Dtool_Methods_CMotionTrail,
    0, // tp_members
    0, // tp_getset
    0, // tp_base
    0, // tp_dict
    0, // tp_descr_get
    0, // tp_descr_set
    0, // tp_dictoffset
    Dtool_Init_CMotionTrail,
    PyType_GenericAlloc,
    Dtool_new_CMotionTrail,
    PyObject_Del,
    0, // tp_is_gc
    0, // tp_bases
    0, // tp_mro
    0, // tp_cache
    0, // tp_subclasses
    0, // tp_weaklist
    0, // tp_del
#if PY_VERSION_HEX >= 0x02060000
    0, // tp_version_tag
#endif
#if PY_VERSION_HEX >= 0x03040000
    0, // tp_finalize
#endif
  },
  TypeHandle::none(),
  Dtool_PyModuleClassInit_CMotionTrail,
  Dtool_UpcastInterface_CMotionTrail,
  Dtool_DowncastInterface_CMotionTrail,
  (CoerceFunction)0,
  (CoerceFunction)0,
};

static void Dtool_PyModuleClassInit_CMotionTrail(PyObject *module) {
  (void) module; // Unused
  static bool initdone = false;
  if (!initdone) {
    initdone = true;
    // Dependent objects
    assert(Dtool_Ptr_TypedReferenceCount != NULL);
    assert(Dtool_Ptr_TypedReferenceCount->_Dtool_ModuleClassInit != NULL);
    Dtool_Ptr_TypedReferenceCount->_Dtool_ModuleClassInit(NULL);
    Dtool_CMotionTrail._PyType.tp_bases = PyTuple_Pack(1, (PyTypeObject *)Dtool_Ptr_TypedReferenceCount);
    PyObject *dict = PyDict_New();
    Dtool_CMotionTrail._PyType.tp_dict = dict;
    PyDict_SetItemString(dict, "DtoolClassDict", dict);
    if (PyType_Ready((PyTypeObject *)&Dtool_CMotionTrail) < 0) {
      Dtool_Raise_TypeError("PyType_Ready(CMotionTrail)");
      return;
    }
    Py_INCREF((PyTypeObject *)&Dtool_CMotionTrail);
  }
}


/**
 * Module Object Linker ..
 */
void Dtool_libp3motiontrail_RegisterTypes() {
  Dtool_CMotionTrail._type = CMotionTrail::get_class_type();
  RegisterRuntimeTypedClass(Dtool_CMotionTrail);
}

void Dtool_libp3motiontrail_ResolveExternals() {
#ifndef LINK_ALL_STATIC
  // Resolve externally imported types.
  Dtool_Ptr_ReferenceCount = LookupRuntimeTypedClass(ReferenceCount::get_class_type());
  Dtool_Ptr_TypeHandle = LookupNamedClass("TypeHandle");
  Dtool_Ptr_TypedObject = LookupRuntimeTypedClass(TypedObject::get_class_type());
  Dtool_Ptr_TypedReferenceCount = LookupRuntimeTypedClass(TypedReferenceCount::get_class_type());
  Dtool_Ptr_LVector4f = LookupRuntimeTypedClass(LVector4f::get_class_type());
  Dtool_Ptr_LMatrix4f = LookupRuntimeTypedClass(LMatrix4f::get_class_type());
  Dtool_Ptr_GeomNode = LookupRuntimeTypedClass(GeomNode::get_class_type());
#endif
}

void Dtool_libp3motiontrail_BuildInstants(PyObject *module) {
  (void) module;
  // CMotionTrail
  Dtool_PyModuleClassInit_CMotionTrail(module);
  PyModule_AddObject(module, "CMotionTrail", (PyObject *)&Dtool_CMotionTrail);
}

static PyMethodDef python_simple_funcs[] = {
  // Support Function For Dtool_types ... for now in each module ??
  {"Dtool_BorrowThisReference", &Dtool_BorrowThisReference, METH_VARARGS, "Used to borrow 'this' pointer (to, from)\nAssumes no ownership."},
  {"Dtool_AddToDictionary", &Dtool_AddToDictionary, METH_VARARGS, "Used to add items into a tp_dict"},
  {NULL, NULL, 0, NULL}
};

struct LibraryDef libp3motiontrail_moddef = {python_simple_funcs};
static InterrogateModuleDef _in_module_def = {
  1478214757,  /* file_identifier */
  "libp3motiontrail",  /* library_name */
  "HtUQ",  /* library_hash_name */
  "panda3d.direct",  /* module_name */
  "libp3motiontrail.in",  /* database_filename */
  (InterrogateUniqueNameDef *)0,  /* unique_names */
  0,  /* num_unique_names */
  (void **)0,  /* fptrs */
  0,  /* num_fptrs */
  1,  /* first_index */
  42  /* next_index */
};

Configure(_in_configure_libp3motiontrail);
ConfigureFn(_in_configure_libp3motiontrail) {
  interrogate_request_module(&_in_module_def);
}

